in1 = str
print ("Command testing")
print ("Opening command: SYSFAQ")
print ("Command type: System Question Board Information")
print ("Command size: 3435 bytes (3.35 Kilobytes)")
print ("Total lines of code used: 54")
print ("Command file format: .py (python file)")
print ("Location: Calculation Error!")
print ("Test the FAQ command")
print ("Type 'SYSFAQ' to try out the command!")
in1 = str(input("FC://"))
if in1 == ("SYSFAQ"):
	print (" ")
	print ("==================================")
	print ("Frequently Asked MEDOS questions")
	print (" ")
	print ("[Q] Why is the drive called: FC? ")
	print ("[A] The FC drive was a <ERROR UNKNOWN>")
	print (" ")
	print ("[Q] Why does the system use \ instead of / ?")
	print ("[A] When we are programming the system, the internal working shows / as a hyperlink when we are putting in the path for the FC drive command. If you reverse the frontslash to a backslash, it won't identify as a hyperlink, and will cause less issues in development. It also adds uniqueness to the system")
	print (" ")
	print ("[Q] Why can't I run games on here?")
	print ("[A] This system was designed for archival purposes (storage) and isn't meant to be used as a system to play games, or work with applications on. It is meant mainly for storage, however it also can be used for fun in virtual machines with its commands and features. If you want an actual OS that does something like that, try something like Windows, Linux, or UNIX")
	print (" ")
	print ("[Q] Will there ever be an SSD version of MEDOS?")
	print ("[A] At the moment, we are not sure. SSD's are NOT made for archival purposes, and that is this systems entire purposes.")
	print (" ")
	print ("[Q] Why do you offer cassette and floppy editions?")
	print ("[A] This system has high legacy options for operating systems from 1980 to 2005. These features are mainly virtual machine based, but if you mount the drive or recognize it as a floppy disk image, it will work as an extended hard drive to your current virtual machine, without even plugging it in to the computer")
	print (" ")
	print ("[Q] Why is it called MEDOS and what does MEDOS mean?")
	print ("[A] MEDOS stands for:")
	print ("<>Meadows")
	print ("<>Disk")
	print ("<>Operating")
	print ("<>System")
	print ("Meadows is the name for our line of operating systems. It resembles freedom, openness, life, and beauty, the things we love about our systems")
	print ("This is just the Command Line Version, Graphical releases of an entirely different Meadows operating system are coming in the future")
	print (" ")
	print ("[Q] Why is the system all command line based and how will this ever be fun or useful?")
	print ("[A] The system is has a CLI (Command Line Interface) as it is meant to be a lightweight storage system, not something to play games, edit, play media, or videos on. We are trying to make it fun, with easter eggs, and stuff like ASCII, BIN, and UNI screensavers")
	print (" ")
	print ("[Q] What is the oldest operating system this system can run with?")
	print ("[A] The oldest operating system MEDOS can work with is BSD 4.0 from 1980, and only works with the Cassette and floppy versions")
	print (" ")
	print (in1)
testconfirm = int(input("Was this information helpful? Y/N "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
   