in1 = str
print ("Command testing")
print ("Test the Windows XP compatibility command")
print ("Type 'XPRUN' to try out the command!")
print ("Warning! Commands are CaSe SeNsItIvE")
in1 = str(input("FC:\\"))
if in1 == ("XPRUN"):
	print ("Windows XP compatibility center")
	print ("A Windows XP no service pack")
	print ("B Windows XP service pack 1")
	print ("C Windows XP Service pack 2")
	print ("D Windows XP Service pack 3")
	print ("E Windows Server 2003")
	print ("F Windows Server 2003 R2")
	print ("G Windows Whistler")
	print ("0 Home edition")
	print ("1 Professional edition")
	print ("2 N edition")
	print ("3 X64 edition")
	print ("4 Starter edition")
	print ("5 Media center edition")
	print ("6 Embedded edition")
	print ("Choose a letter A-G followed by a number 0-6 then click enter to continue compatibility testing")
	print ("Type XE to quit")
	print (in1)
testconfirm = int(input("Did the command info look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
   