print ("Opening command: DOSTOP")
print ("Command type: Display location")
print ("Command size: 10450 bytes (10.2 Kilobytes)")
print ("Total lines of code used: 87")
print ("Command file format: .py (python file)")
print ("Location: Calculation Error!")
print ("This command gives you a desktop completely in ASCII format")
print ("Type 'DOSTOP' to try out command")
in1 = str(input("FC://"))
if in1 == ("DOSTOP"):
	print ("                                                                               																						  ")
	print ("                                                                               																						  ")
	print ("                                                                               																						  ")
	print ("                                                                               																						  ")
	print ("   [][][][]                                                                            																				  ")
	print (" [][][][][][]                                                                  																					      ")
	print (" []##|##|##[]                                                                              																			  ")
	print (" []##|##|##[]                                                                             																			  ")
	print (" [][][][][][]                                                                              																			  ")
	print (" FILEFURNACE.BIN                                                                              																		  ")
	print ("                                                                                																				      ")
	print (" ()_______()                                __   ___ ____                                                                  											  ")
	print (" |SYS      |                               /_ | / _ \___ \                                    																	      ")
	print (" |SET      |                               | || | | |__) |                                     																		  ")
	print (" ()-()-()-()                               | || | | |__ <                                                                 							     		``	  ")
	print (" SETTINGS.PY                                 || |_| |__) |																			                                  ")
	print (" _________                                 |_(_)___/____/ 																			                                  ")
	print (" [ //    ]                              																			                                                  ")
	print (" [ \\    ]                             																				                                                  ")
	print (" [_______]           	               																				                                                  ")
	print (" PROGRAMS.DIR      							                                                             													          ")
	print ("                                                                                																				      ")
	print ("  ******                                                                        																			          ")
	print (" %%%%%%%%%                                                                     																					      ")
	print (" %%%[o]%%%                                                                     																					      ")
	print (" %%%%%%%%%                                                             																					        	  ")
	print (" ICON.BMP                                                       																			                    	  ")
	print ("______________________________________________________________________________________________________________________________________________________________________")
	print ("[TERMINAL] MEDOS Desktop Beta 1 | Test demo mode only |                                                                                                      |3:55 pm|")
	print ("======================================================================================================================================================================")
	print ("																																									   ")                                                                                                                          
	print ("																																									   ")                                                                                                                           
	print ("PPPPPPPPPPPPPPPPP        AAA           UUUUUUUU     UUUUUUUU   SSSSSSSSSSSSSSS EEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDD    												       ")     
	print ("P0000000000000000P      A000A          U000000U     U000000U SS000000000000000SE00000000000000000000ED000000000000DDD                                                      ")
	print ("P000000PPPPPP00000P    A00000A         U000000U     U000000US00000SSSSSS000000SE00000000000000000000ED000000000000000DD                                                    ")
	print ("PP00000P     P00000P  A0000000A        UU00000U     U00000UUS00000S     SSSSSSSEE000000EEEEEEEEE0000EDDD00000DDDDD00000D                                                   ")
	print (" P0000P     P00000P A000000000A        U00000U     U00000U S00000S              E00000E       EEEEEE  D00000D    D00000D                                                   ")
	print ("  P0000P     P00000PA00000A00000A       U00000D     D00000U S00000S              E00000E               D00000D     D00000D                                                 ")
	print ("   P0000PPPPPP00000PA00000A A00000A      U00000D     D00000U  S0000SSSS           E000000EEEEEEEEEE     D00000D     D00000D                                                ")
	print ("  P0000000000000PPA00000A   A00000A     U00000D     D00000U   SS000000SSSSS      E000000000000000E     D00000D     D00000D                                                 ")
	print ("  P0000PPPPPPPPP A00000A     A00000A    U00000D     D00000U     SSS00000000SS    E000000000000000E     D00000D     D00000D                                                 ")
	print ("  P0000P        A00000AAAAAAAAA00000A   U00000D     D00000U        SSSSSS0000S   E000000EEEEEEEEEE     D00000D     D00000D												   ")
	print ("  P0000P       A000000000000000000000A  U00000D     D00000U             S00000S  E00000E               D00000D     D00000D                                                 ")
	print ("  P0000P      A00000AAAAAAAAAAAAA00000A U000000U   U000000U             S00000S  E00000E       EEEEEE  D00000D    D00000D                                                  ")
	print ("PP000000PP   A00000A             A00000AU0000000UUU0000000U SSSSSSS     S00000SEE000000EEEEEEEE00000EDDD00000DDDDD00000D                                                   ")
	print ("P00000000P  A00000A               A00000AUU0000000000000UU  S000000SSSSSS00000SE00000000000000000000ED000000000000000DD                                                    ")
	print ("P00000000P A00000A                 A00000A UU000000000UU    S000000000000000SS E00000000000000000000ED000000000000DDD                                                      ")
	print ("PPPPPPPPPPAAAAAAA                   AAAAAAA  UUUUUUUUU       SSSSSSSSSSSSSSS   EEEEEEEEEEEEEEEEEEEEEEDDDDDDDDDDDDD 		       											   ")         
	print ("																																										   ")                                                                                                                          
	print ("																																										   ")  
	print ("																																										   ")
	print ("  _____            _    _                _             _       																											   ")                    
	print (" |  __ \          | |  | |              (_)           | |                          																						   ")
	print (" | |  | | ___  ___| | _| |_ ___  _ __    _ ___    __ _| |__   _____   _____        																						   ")
	print (" | |  | |/ _ \/ __| |/ / __/ _ \| '_ \  | / __|  / _` | '_ \ / _ \ \ / / _ \       																						   ")
	print (" | |__| |  __/\__ \   <| || (_) | |_) | | \__ \ | (_| | |_) | (_) \ V /  __/       																						   ")
	print (" |_____/ \___||___/_|\_\\__\___/| .__/ _|_|___/  \__,_|_.__/ \___/ \_/ \___| _ _   																						   ")
	print ("                                | |   | |            | |                    (_) |  																						   ")
	print ("  _ __  _ __ ___  ___ ___    ___|_|__ | |_ ___ _ __  | |_ ___     __ _ _   _ _| |_ 																						   ")
	print (" | '_ \| '__/ _ \/ __/ __|  / _ \ '_ \| __/ _ \ '__| | __/ _ \   / _` | | | | | __|																						   ")
	print (" | |_) | | |  __/\__ \__ \ |  __/ | | | ||  __/ |    | || (_) | | (_| | |_| | | |_ 																						   ")
	print (" | .__/|_|  \___||___/___/  \___|_| |_|\__\___|_|     \__\___/   \__, |\__,_|_|\__|																						   ")
	print (" | |                | | |               | |              (_)        | |            																						   ")
	print (" |_|_  ___ _ __ ___ | | |  _   _ _ __   | |_ ___   __   ___  _____  |_| __         																						   ")
	print (" / __|/ __| '__/ _ \| | | | | | | '_ \  | __/ _ \  \ \ / / |/ _ \ \ /\ / /         																						   ")
	print (" \__ \ (__| | | (_) | | | | |_| | |_) | | || (_) |  \ V /| |  __/\ V  V /          																						   ")
	print (" |___/\___|_|  \___/|_|_|  \__,_| .__/   \__\___/    \_/ |_|\___| \_/\_/           																						   ")
	print ("                                | |  																																	   ")                                              
	print ("                                |_|  																																	   ")
	print ("																																										   ")
	print ("===========================================================================================================================================================================")   
testconfirm = int(input("Pause mode, follow above instructions please"))                                      
if testconfirm == 1:
    print ("Command test successful!")
    print ("Exiting...")
else:
    print ("Shutting down")