in1 = int
in1 = 1
print ("Current directory")
print ("Type 'ENTER' to view")
in2 = str(input("FC://"))
if in2 == ("ENTER"):
	while (in1 == 1):
		print ("Contents of FCDRIVE")
		print ("System")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>DOSTOP")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>DOSTOP>Dostop command.py  | 10,450 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>DOSTOP>Total size: 10,450 bytes (10.2 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>DOSTOP>Wallpapers")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>DOSTOP>Wallpapers>Blisscii preview.py")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>DOSTOP>Wallpapers>Blisscii.txt")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>DOSTOP?Wallpapers> total size: 19,470 bytes (19.0 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>Integers")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>8 Bit test 1x.py  | 1,187 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>16 Bit test 1x.py  |  1,210 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>32 Bit test 1x.py  | 1,269 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>DOSTOP command.py  | 10,450 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>INTCOMP command.py  | 31,138 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>Testconfirm.py  | 261 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug>Total size: 45,515 bytes (44.4 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Debug Total size: 131,362 bytes (128 KB) 17 files + 3 folders = 20 items")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Programs")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Programs>(empty)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Programs>Total size: 0 bytes (0 KB) 0 files + 0 folders = 0 items")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Screensavers")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Screensavers>ASCII art")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Screensavers>ASCII art>DNA Screensaver.py  | 741 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Screensavers>ASCII art>Pinefall screensaver.py  | 2,297 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Screensavers>ASCII art>Platformers sky screensaver.py  | 651 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Screensavers>ASCII art>Total size: 3,689 bytes (3.60 Kilobytes") 
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Screensavers>Binary art")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Screensavers>Binary art>7 nation army binary screensaver.py  | (8,139 bytes (7.94 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Screensavers>Unicode art")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Screensavers>Unicode art>(empty)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Screensavers total size: 11,828 bytes (11.5 Kilobytes) 4 items + 3 folders = 7 items")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Linux 86x64")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Linux 86x64>audacity-minsrc-2.2.2.tar.xz  | 8,210,700 bytes (8,210.70 Kilobytes) (7.83 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Linux 86x64>Python-3.6.4.tar.xz  | 16,992,824 bytes (16,992.82 Kilobytes) (16.2 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Linux 86x64>Python-3.6.4.tgz  | 22,710,891 bytes  | 22,710.89 kilobytes) (21.6 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Stsrem12>Linux 86x64 Total size: 47,914,415 bytes (47,914,41 kilobytes) (45.6 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Mac 86x64")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Mac 86x64>audacity-macos-2.2.2.dmg  | 34,240,434 bytes (34,240.43 Kilobytes) (32.6 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Mac 86x64>python-3.6.4-macosx10.6.pkg  | 27,778,156 bytes (27,778.15 bytes) (26.4 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Mac 86x64 total size: (62,018,590 bytes) (62,018.59 bytes) (59.1 MB) 2 files + 0 dolders = 2 items")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Porting plans")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Porting plans>(empty)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Porting plans Total size: 0 bytes (0 Kilobytes) 0 files + 0 folders = 0 items")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Windows 32 bit")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Windows 32 bit>python-3.6.4.exe  | 30,653,888 bytes (30,653.88 kilobytes) (29.2 MB)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Windows 32 bit>python-3.6.4-embed-win32.zip  | (6,400,788 bytes (6,400.78 kilobytes) (6.10 megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Windows 32 bit>python-3.6.4-webinstall.exe  | 1,294,088 bytes (1,294.08 kilobytes) (1.23 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Windows 32 bit Total size: 38,348,764 bytes (38,348.76 kilobytes) 36.5 Megabytes) 3 files + 0 folders = 3 items")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Windows 86x64")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Windows 86x64>audacity-win-2.2.2.exe  | 20,248,056 bytes (20,248,05 Kilobytes) (19.3 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Windows 86x64>audacity-win-2.2.2.zip  | 11,979,029 bytes (11,979.02 kilobytes) (11.4 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Windows 86x64>python-3.6.4-amd64.exe  | (31,684,744 bytes (31,684.74 kilobytes) (30.2 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Windows 86x64>python-3.6.4-embed-amd64.zip  | 7,162,335 bytes (7,162.33 kilobytes) (6.83 megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Windows 86x64>python364.chm  | (8,041,937 bytes (8,041.93 kilobytes) (7.66 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12>Windows 86x64 Total size: 79,116,101 bytes  (79.116.10 kilobytes) (75.4 Megabytes) 5 files + 0 folders = 5 items")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>System12 total size: 227,397,870 bytes (227397.86 Kilobytes) (216 Megabytes) 13 files + 5 folders = 18 items")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>3.RUN Command.py  | 917 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>9XRUN command.py  | 919 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>ANDRORUN command.py  | 1,248 bytes (1.2 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>DIR command.py  | 776 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>IORUN command.py | 904 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>CD command.py  | 913 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>MASYSRUN command.py  | 1021 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>CRED Command.py  | 1031 bytes (1.0 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>MCXRUN command.py   | 1080 bytes (1.0 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>XPRUN command.py  | 1,164 bytes (1.1 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>CALC command.py  | 1,209 bytes (1.2 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>V7RUN command.py  | 1,278 bytes (1.2 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>TASKMAN command.py  | 1,229 bytes (1.2 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>COMPBLOG command.py  | 1,431 bytes (1.4 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>UBURUN command.py  | 1,469 bytes (1.4 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>SECURINF command.py  | 1,777 bytes (1.7 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>TLDINF command.py  | 2,163 bytes (2.1 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>BGUIDE command.py  | 3,156 bytes (3.1 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>SYSFAQ command.py  | 3,435 bytes (3.4 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>CMNDTEST command.py  | 4,654 bytes (4.6 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>DEL command.py  | 5,755 bytes (5.6 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>KBRDTEST command.py  | 6,987 bytes (6.9 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>UDINFBTA command old.py  | 7,824 bytes (7.8 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>SYSSETS command.py  | 9,202 bytes (9.2 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>SYSCRASH%7 command.py  | 10,877 bytes (10.8 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>HELP command.py  | 12,039 bytes (12.0 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>UDINFBTA command.py  | 17,548 bytes (17.1 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands>INTCOMP command.py  | 31,138 bytes (31.1 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Commands Total size: 133,234 bytes (133.2 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Functional features in this build")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Functional features in this build>COMPBLOG command.py  | 1,628 bytes (1.6 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Functional features in this build>HELP command.py  |  1,984 bytes (1.9 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Functional features in this build>OS Shell 1.0.py  | 4,057 bytes (4.0 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Functional features in this build>Setuptest2.py  |  30,176 bytes (30.1 Kilobytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Functional features in this build Total size: 37,845 bytes (37.8 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>BULIN1.txt  | 3,814 bytes (3.8 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>BUULIN1.txt  | 4,317 bytes (4.3 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Setup Test 1.py  | 29,974 bytes (29.9 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Setuptest2.py  | (30,176 bytes (30.1 Kilobytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test>Test.py  | 369 bytes")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM>Test> Total size: 68,650 bytes (68.6 Kilobytes) 5 files + 2 folders = 7 items")
		print ("FC:\\CurrentBuild>Developer>1SYSTEM-- Total size of 1SYSTEM: 227,788,580 bytes (227,788.57 kilobytes) (217 megabytes)")
# Directory #2 (extras)
		print ("Contents of 2EXTRAS")
		print ("System")
		print (">FC:\\CurrentBuild>Developer>Extras>Extras")
		print (">FC:\\CurrentBuild>Developer>Extras>Extras>DOSTOP 1.0.png  | 12,371 bytes (12.37 Kilobytes)")
		print (">FC:\\CurrentBuild>Developer>Extras>Extras>Logo.bmp  | 5,318 bytes (5.31 Kilobytes)")
		print (">FC:\\CurrentBuild>Developer>Extras>Extras>MEDOS Build 2 VS MSDOS 10.0.png  | 95,869 bytes (95.86 Kilobytes)")
		print (">FC:\\CurrentBuild>Developer>Extras>Extras Total size = 113,558 bytes (113.55 kilobytes) 3 files + 0 folders = 3 items")
		print (">FC:\\CurrentBuild>Developer>Extras>1.03.txt  | 154 bytes")
		print (">FC:\\CurrentBuild>Developer>Extras>DNA circle.txt  | 163 bytes")
		print (">FC:\\CurrentBuild>Developer>Extras>Set up a connection.txt  | 2,379 bytes (2.37 Kilobytes)")
		print (">FC:\\CurrentBuild>Developer>Extras>Setup.txt  | 29,908 bytes (29.90 Kilobytes)")
		print (">FC:\\CurrentBuild>Developer>Extras>Source.txt  | 15,822 bytes (15.82 Kilobytes)")
		print (">FC:\\CurrentBuild>Developer>Extras>Test.py  | 11,515 bytes (11.51 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Current Directory 2EXTRAS.PY  | 1,358 bytes (1.31 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer> Total size: 61,299 bytes (61.29 Kilobytes) 6 files + 0 folders = 7 items")
		print ("FC:\\CurrentBuild>Developer>-- Total size of 2EXTRAS: 174,857 bytes (174.85 Kilobytes) 10 files + 1 folder = 11 items")
# directory 3 (Logs)
		print ("Contents of 3LOGS")
		print ("System")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>0.9 Differences between ASN")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>0.9 Differences between ASN>Autonomous_system_(Internet).pdf  | 142,195 bytes (142.19 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>0.9 Differences between ASN>MEDOS Differences with ASN.txt  | 1,196 bytes (1.19 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>0.9 Differences between ASN Total size: 143,391 bytes (143.39 KilobyteS) 2 files + 0 folders = 2 items")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.0 Support")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.0 Support>Support.rtf  | 52,729 bytes (52.72 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.0 Support Total size: 52,729 bytes (52.72 Kilobytes) 1 file + 0 folders = 1 item")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.1 Purpose")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.1 Purpose>Current concept.rtf  | 4,600 bytes (4.60 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.1 Purpose Total size: 4,600 bytes (4.60 Kilobytes) 1 file + 0 folders = 1 item")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.2 Help Command")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.2 Help command>HELP command.py  | 1,984 bytes (1.98 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.2 Help command Total size: 1,984 bytes (1.98 Kilobytes) 1 file + 0 folders - 1 item")	
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.3 File compatibility log command")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.3 File compatibility log command>COMPBLOG Command.py  | 1,628 bytes (1.62 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.3 File compatibility log command Total size: 1,628 bytes (1.62 Kilobytes) 1 file + 0 folders = 1 item")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.4 Update information for beta versions command")	
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.4 Update information for beta versions command>UDINFBTA command.py  | 5,016 bytes (5.01 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Logs>Documentation>1.4 Update information for beta versions total size: 5,016 bytes (5.01 Kilobytes) 1 file + 0 folders = 1 item")
		print ("FC:\\CurrentBuild>Developer>Logs>Contents of 3LOGS.PY  | 2,581 bytes (2.58 kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Logs Total size: 0 bytes")
		print ("FC:\\CurrentBuild>Developer-- Total size of Logs = 206,767 bytes (206.76 kilobytes) 8 files + 6 folders = 14 items")
# Directory 4 pictures
		print ("FC:\\CurrentBuild>Developer>Pictures>(this folder is empty)")
# Directory 5 (video)
		print ("FC:\\CurrentBuild>Developer>Video>(this folder is empty)")
# Directory 6 (documents)
		print ("FC:\\CurrentBuild>Developer>Documents>(this folder is empty)")
# Directory 7 (audio)
in1 = str
print ("Current directory")
print ("Type 'ENTER' to view")
in1 = str(input("FC://"))
if in1 == ("ENTER"):
		print ("Contents of 7AUDIO")
		print ("System")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project_data")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project_data>e08")	
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project_data>e08>d08")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08>e0808abd.au  | 1,060,956 bytes (1,060.95 Kilobytes) (1.06 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08>e0808ac8.au  | 1,060,956 bytes (1,060.95 Kilobytes) (1.06 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08>e0808b54.au  | 1,060,956 bytes (1,060.95 Kilobytes) (1.06 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08>e0808bbb.au  | 1,060,956 bytes (1,060.95 Kilobytes) (1.06 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08>e0808bd1.au  | 587,656 bytes (587.65 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08>e0808e48.au  | 220,216 bytes (220.21 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08>e08083a1.au  | 587,656 bytes (587.65 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08>e080836e.au  | 1,060,956 bytes (1,060.95 Kilobytes) (1.06 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08>e080865d.au  | 1,060,956 bytes (1,060.95 Kilobytes) (1.06 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08>e0808362.au  | 1,060,956 bytes (1,060.95 Kilobytes) (1.06 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08>e0808548.au  | 220,216 bytes (220.21 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08>e0808797.au  | 1,060,956 bytes (1,060.95 Kilobytes) (1.06 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project data>e08>d08 Total size: 10,103,392 bytes (10,103.39 kilobytes) (10.10 Megabytes) 12 files + 0 folders = 12 items")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver project.auo  | 3,411 bytes (3.41 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver.m4a  | 492,324 bytes (492.32 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources>Connecting to receiver.wav  | 5,460,046 bytes (5,460.04 Kilobytes) (5.20 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Sources Total size: 5,955,781 bytes (5,955.78 Kilobytes) (5.67 Megabytes) 3 files + 0 folders = 3 items")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection>Connecting to receiver.wav | album #3 | MEDOS System by Sean Walla Walla | 9,979,934 bytes (9,979.93 Kilobytes) (9.51 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Connection Total size: 9,979,934 bytes (9,979.93 Kilobytes) (9.51 Megabytes) 1 file + 0 folders = 1 item")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>Sources")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>Sources>RECYCLE.m4a  | 82,686 bytes (82.68 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>Sources>RECYCLE.wav  | 901,198 bytes (901.19 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>Sources>Windows 98 chord.m4a  | 41,277 bytes (41.27 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>Sources>Windows 98 chord.wav  | 450,638 bytes (450.63 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>Sources Total size: 1,475,799 bytes (1,475.79 Kilobytes) (1.47 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08>e0808a48.au  | 23,760 bytes (23.76 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08>e0808bae.au  | 23,760 bytes (23.76 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08>e0808c04.au  | 78,848 bytes (78.84 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08>e0808fa4.au  | 78,848 bytes (78.84 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08>e08082d9.au  | 4,632 bytes (4.63 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08>e08085d5.au  | 8,004 bytes (8.00 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08>e08086d7.au  | 5,316 bytes (5.31 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08>e08087f9.au  | 5,316 bytes (5.31 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08>e080802a.au  | 18,884 bytes (18.88 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08>e080866b.au  | 8,004 bytes (8.00 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08>e0808136.au  | 4,632 bytes (4.63 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08>e0808908.au  | 18,884 bytes (18.88 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project_data>e08>d08 total size: 278,888 bytes (278.88 kilobytes) 12 files + 0 folders = 12 items")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>CDVDRAYCheck .wav  | # 9 | MEDOS System by Sean Walla Walla | 10,603,674 bytes (10,613.67 kilobytes) (10.61 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>Chord.wav | # 8 | MEDOS System by Sean Walla Walla | 901,562 bytes (901.56 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>Dead Chirp .wav | # 4294967295 (-1) | MEDOS System by Sean Walla Walla | 11,258,022 bytes (11,258.02 Kilobytes) (11.25 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>Exclamation .wav | # 7 | MEDOS System by Sean Walla Walla | 252,610 bytes (252.61 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>Floppy check.wav | # 10 | MEDOS System by Sean Walla Walla | 5,629,180 bytes (5,629.18 Kilobytes) (5.62 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A project.aup  | 62,270 bytes (62.27 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>System crash type A.wav  | # 4 | MEDOS System by Sean Walla Walla | 3,839,766 bytes (3,839.76 Kilobytes) (3.83 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>Virus Detected .wav  | # 5 | MEDOS System by Sean Walla Walla | 901,562 bytes (901.56 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors>Virus removed .wav  | # 6 | MEDOS System by Sean Walla Walla | 759,002 bytes (759.00 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Errors Total size: 34,207,648 bytes (34,207.64 Kilobytes) (34.20 Megabytes) 9 files + 2 folders = 11 items")
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album")
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album>Startup sound official.wav  | # 1 | MEDOS System by Sean Walla Walla | 2,802,096 bytes (2,802.09 Kilobytes) (2.80 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album>Shutdown sound.wav  | # 2 | MEDOS System by Sean Walla Walla | 922,030 bytes (922.03 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album>Connecting to receiver.wav  | # 3 | MEDOS System by Sean Walla Walla | 9,979,934 bytes (9,979.93 Kilobytes) (9.97 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album>System crash type A.wav  | # 4 | MEDOS System by Sean Walla Walla | 3,839,766 bytes (3,839.76 Kilobytes) (3.83 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album>Virus Detected .wav  | # 5 | MEDOS System by Sean Walla Walla | 901,562 bytes (901.56 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album>Virus removed .wav  | # 6 | MEDOS System by Sean Walla Walla | 759,002 bytes (759.00 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album>Exclamation .wav  | # 7 | MEDOS System by Sean Walla Walla | 252,610 bytes (252.61 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album>Chord.wav  | # 8| MEDOS System by Sean Walla Walla | 901,562 bytes (901.56 Kilobytes)") 
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album>CDVDRAYCheck .wav  | # 9 | MEDOS System by Sean Walla Walla | 10,603,674 bytes (10,603.67 Kilobytes) (10.60 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album>Floppy check.wav  | # 10 | MEDOS System by Sean Walla Walla | 5,629,180 bytes (5,629.18 Kilobytes) (5.62 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album>Dead Chirp .wav   | # -1 | MEDOS System by Sean Walla Walla | 11,258,022 bytes (11,258.02 Kilobytes) (11.25 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>MEDOS System Beta 1 complete album Total Size: 47,849,438 bytes (47,849.43 Kilobytes) (47.84 Megabytes) 11 files + 0 folders = 11 items")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Shutdown sound project_data")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Shutdown sound project_data>e08")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Shutdown sound project_data>e08>d08")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Shutdown sound project_data>e08>d08>e0808b57.au  | 933,980 bytes (933.98 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Shutdown sound project_data>e08>d08>e0808b99.au  | 456,772 bytes (456.77 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Shutdown sound project_data>e08>d08>e0808fb6.au  | 110,548 bytes (110.54 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Shutdown sound project_data>e08>d08>e08086f5.au  | 933,980 bytes (933.98 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Shutdown sound project_data>e08>d08>e0808640.au  | 456,772 bytes (456.77 Kiloybytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Shutdown sound project_data>e08>d08>e0808748.au  | 864,348 bytes (864.34 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Shutdown sound project_data>e08>d08>e0808782.au  | 864,348 bytes (864.34 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Shutdown sound project_data>e08>d08 Total Size: 4,620,748 bytes (4,620.74 Kilobytes) (4.62 Megabytes) 7 files + 0 folders = 7 items")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Goodbye.wav  | 53,754 bytes (53.75 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Mac 1994.m4a  | 41,709 bytes (41.70 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Mac 1994.wav  | 450,638 bytes (450.63 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>NT 5 Shutdown.m4a  | 77,573 bytes (77.57 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>NT 5 Shutdown.wav  | 852,046 bytes (852.04 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Shutdown sound project.aup  | 4,411 bytes (4.41 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Ubuntu shutdown pre-12.0.m4a  | (83,652 bytes (83.65 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources>Ubuntu shutdown pre-12.0_0.wav  | (921,678 bytes (921.67 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Sources Total size: 2,485,461 bytes (2,485.46 Kilobytes) (2.48 Megabytes) 8 files + 1 folder = 9 items")
		print ("FC:\\CurrentBuild>Developer>Audio>Shutdown>Shutdown sound.wav | # 2 | MEDOS System by Sean Walla Walla | 922,030 bytes (922.03 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>shutdown Total size: 922,030 bytes (922.03 Kilobytes) 1 file + 1 folder = 2 items")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08>e0808ad6.au  | 337,988 bytes (337.98 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08>e0808b3c.au  | 1,060,956 bytes (1,060.95 Kilobytes) (1.06 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08>e0808c77.au  | 358,468 bytes (358.46 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08>e0808e67.au  | 549,968 bytes (549.96 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08>e0808eca.au  | 549,968 bytes (549.96 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08>e0808eeb.au  | 111,776 bytes (111.77 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08>e08082c6.au  | 358,468 bytes (358.46 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08>e08089cf.au  | 1,060,956 bytes (1,060.95 Kilobytes) (1.06 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08>e080850b.au  | 1,060,956 bytes (1,060.95 Kilobytes) (1.06 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08>e0808097.au  | 1,060,956 bytes (1,060.95 Kilobytes) (1.06 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08>e0808229.au  | 337,988 bytes (337.98 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 _data>e08>d08 Total size: 6,848,448 bytes (6,848.44 Kilobytes) (6.84 Megabytes) 11 files + 0 folders = 11 items")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Audacity Project 2 .aup  | 5,034 bytes (5.03 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>audio.wav  | 54,368 bytes (54.36 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Old UBUNTU startup sound.m4a  | 124,926 bytes (124.92 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>Old UBUNTU startup sound.wav  | 1,380,430 bytes (1,380.43 kilobytes) (1.38 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>videoplayback (1).m4a  | 49,430 bytes (49.43 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>videoplayback (1).wav  | (540,750 bytes (540.75 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>videoplayback.m4a  | 127,073 bytes (127.07 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources>videoplayback.wav  | 1,400,910 bytes (1,400.91 Kilobytes) (1.40 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Sources Total size: 3,682,921 bytes (3,682.92 Kilobytes) (3.68 Megabytes) 8 files + 1 folder = 9 items")	
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Notes.txt  | 508 bytes")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Part 1.wav  | 2,760,898 bytes (2,760.89 Kilobytes) (2.76 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>Startup sound official.wav | # 1 | MEDOS System by Sean Walla Walla | 2,802,096 bytes (2,802.09 Kilobytes) (2.80 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup>startup sound.wav  | (2,801,858 bytes (2,801.85 Kilobytes) (2.80 Megabytes)")
		print ("FC:\\CurrentBuild>Developer>Audio>Startup Total size: 8,365,360 bytes (8,365.36 Kilobytes) (8.36 Megabytes) 4 files + 1 folder = 5 items")
		print ("FC:\\CurrentBuild>Developer>Audio>Current Directory 7AUDIO.py  | 14741 bytes (14.74 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>Audio Total size: 2000 bytes (2.00 kilobytes) 1 file + 0 folders = 1 item")
		print ("FC:\\CurrentBuild>Developer>Audio -- Total size of 7AUDIO: 136,790,589 bytes (136,790.58 Kilobytes) (136.79 megabytes) 100 files + 55 folders = 155 items")
# Directory 8 (Other)
		print ("FC:\\CurrentBuild>Developer>Documents>(this folder is empty)")
# Mainframe 
		print ("FC:\\CurrentBuild>Developer>DIRSORT.INI  | 0 bytes")
		print ("FC:\\CurrentBuild>Developer>FC Directory list.py  | 20000 bytes (20.00 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>SYSBOOT5.py  | 107,364 bytes (107.36 Kilobytes)")
		print ("FC:\\CurrentBuild>Developer>-- Contents : ")
		print ("FC:\\CurrentBuild -- contents = bytes, (kilobytes) (megabytes) 184 files + 55 folders = ")
		in1 + 0
else:
	testconfirm = int(input("That was the entire FC directory listing. To exit, type the number 1 then click enter "))
if testconfirm == 1:
    print ("EXITING")
    print ("EXITING")
else:
    print ("EXITING")
testconfirm = int(input("Did the command info look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
   
