in1 = str
print ("Command testing")
print ("Test the Delete command")
print ("Type 'DEL' to try out the command!")
in1 = str(input("FC://"))
if in1 == ("DEL"):
	print ("Test the delete command")
	print ("We have placed a fake file in the current directory")
	print ("Don't worry, this file is nonexistant, it is just for the demo")
	print ("Type DEL:TEST.TXT to start to delete it")
	print ("{system} inserting 'DIR' command")
	print ("FC:\\Demo\\DIR")
	print ("Contents of FC Demo")
	print ("TEST.TXT 0 bytes")
in1 = str(input("FC://")
if in1 == ("DEL:TEST.TXT"):
	print ("Are you sure you want to delete this file? This cannot be undone (Y/N)")
in1 = str(input("ANSWER:")
if in1 == ("Y")
	print ("Successfully deleted file")
	print (" ")
	print ("Now we will show you more files and how to delete them")
	print ("We have placed a Cache file in the directory")
	print ("Just like last time, the file is nonexistant, and only for the demo")
	print ("Type DEL:TEST.CACHE to start to delete it")
	print ("{system} inserting 'DIR' command")
	print ("FC:\\Demo\\DIR")
	print ("Contents of FC Demo")
	print ("TEST.CACHE 0 bytes")
in1 = str(input("FC://")
if in1 == ("DEL:TEST.CACHE"):
	print ("Are you sure you want to clear this file? This cannot be undone (Y/N)")
in1 = str(input("ANSWER:")
if in1 == ("Y")
	print ("Successfully deleted file")
	print (" ")
	print ("Now we will show you more files and how to delete them")
	print ("This time we have something serious to show and teach you:")
	print ("System files!")
	print ("Note: You really shouldn't randomly delete system files, they WILL cause damage")
	print ("Before deleting one, make sure it is not connected to anything, and MAKE sure you know what you are doing")
	print ("If you are using a virtual machine, you can delete them all you want, as long as you know what you are doing")
	print ("Just like last time, the file is nonexistant, and only for the demo")
	print ("This file is fake, and won't harm your system")
	print ("Type DEL:TEST.SYS to start to delete it")
	print ("{system} inserting 'DIR' command")
	print ("FC:\\Demo\\DIR")
	print ("Contents of FC Demo")
	print ("TEST.SYS 0 bytes")
in1 = str(input("FC://")
if in1 == ("DEL:TEST.SYS"):
	print ("{System} inserting 'ADRANK' command")
	print (" ")
	print ("You are now an administrator to this system (demo only)")
	print (" ")
	print ("WARNING! This is a system file! Make sure you know what you are doing before you delete/modify it")
	print ("Are you sure you want to clear this file? This cannot be undone (Y/N)")
in1 = str(input("ANSWER:")
if in1 == ("Y")
	print ("Successfully deleted file")
	print (" ")
	print ("Now we will show you more files and how to delete them")
	print ("This time, we are working with zipped files")
	print ("Just like last time, the file is nonexistant, and only for the demo")
	print ("This file is fake, and won't harm your system")
	print ("Note: zipped files can contain multiple files inside of them. You should have a backup if it is important")
	print ("Type DEL:TEST.ZIP to start to delete it")
	print ("{system} inserting 'DIR' command")
	print ("FC:\\Demo\\DIR")
	print ("Contents of FC Demo")
	print ("TEST.ZIP 500 bytes")
in1 = str(input("FC://")
if in1 == ("DEL:TEST.ZIP"):
	print ("{System} inserting 'ADRANK' command")
	print (" ")
	print ("You are already an administrator to this system (demo only)")
	print (" ")
	print ("WARNING! This is a zipped file! Make sure you know what you are doing before you delete/modify it")
	print ("This zip archive contains: 8 files")
	print ("Are you sure you want to clear this file? This cannot be undone (Y/N)")
in1 = str(input("ANSWER:")
if in1 == ("Y")
	print ("Deleting PIC.JPEG")
	print ("Deleting SECUR.MP4")
	print ("Deleting SFX.MP3")
	print ("Deleting TEST.PDF")
	print ("Deleting NIGHT.GIF")
	print ("Deleting SOURCE.TXT")
	print ("Deleting CACHE.0")
	print ("Deleting HOME.HTML")
	print ("Successfully deleted file(s)")
	print (" ")
	print ("Now we will show you one last thing to delete")
	print ("This time, we are working with folders")
	print ("Just like last time, the file is nonexistant, and only for the demo")
	print ("This file is fake, and won't harm your system")
	print ("Note: folders can contain multiple files inside of them. You should have a backup if it is important")
	print ("Type FC:\\DEMO\\FOL:DELTREE-ALL to start to delete it")
	print ("{system} inserting 'DIR' command")
	print ("FC:\\Demo\\DIR")
	print ("Contents of FC Demo")
	print ("TEST.ZIP 500 bytes")
in1 = str(input("FC://")
if in1 == ("FC:\\DEMO\\FOL:DELTREE-ALL"):
	print ("{System} inserting 'ADRANK' command")
	print (" ")
	print ("You are already an administrator to this system (demo only)")
	print (" ")
	print ("WARNING! This is a folder. Make sure you know what you are doing before you delete/modify it")
	print ("This folder contains: 8 files")
	print ("Are you sure you want to clear this file? This cannot be undone (Y/N)")
in1 = str(input("ANSWER:")
if in1 == ("Y")
	print ("Deleting PIC.JPEG")
	print ("Deleting SECUR.MP4")
	print ("Deleting SFX.MP3")
	print ("Deleting TEST.PDF")
	print ("Deleting NIGHT.GIF")
	print ("Deleting SOURCE.TXT")
	print ("Deleting CACHE.0")
	print ("Deleting HOME.HTML")
	print ("Successfully deleted file(s)")
	print (" ")
	print ("Great, now you know how to delete!")
	print ("The command worked!")	
print (in1)
testconfirm = int(input("Did the setup look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("System setup successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
    