in1 = str
print ("Command testing")
print ("Test the iOS compatibility command")
print ("Type 'IORUN' to try out the command!")
print ("Warning! Commands are CaSe SeNsItIvE")
in1 = str(input("FC:\\"))
if in1 == ("IORUN"):
	print ("iOS compatibility center")
	print ("0 iOS 1")
	print ("1 iOS 2")
	print ("2 iOS 3")
	print ("3 iOS 4")
	print ("4 iOS 5")
	print ("5 iOS 6")
	print ("6 iOS 7")
	print ("7 iOS 8")
	print ("8 iOS 9")
	print ("9 iOS 10")
	print ("A iOS 11")
	print ("B iOS 12")
	print ("Choose a number 0-9 or A-B then click enter to continue compatibility testing")
	print ("Type XE to quit")
	print (in1)
testconfirm = int(input("Did the command info look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
   