in1 = str
print ("Command testing")
print ("Test the Security info command")
print ("Type 'SECURINF' to try out the command!")
in1 = str(input("FC://"))
if in1 == ("SECURINF"):
	print ("MEDOS Security center")
	print (" ")
	print ("OS version: 3")
	print ("Language: Python 3.6")
	print ("This is a demo build, network security is not measured, as this build was not intended to connect to the internet")
	print ("It can be modified to do so, but would be pointless. Security is measured as 'Missing'")
	print (" ")
	print ("Windows 3.x")
	print ("Security level: ?")
	print ("Security patch: 0")
	print (" ")
	print ("Windows 9x")
	print ("Security level: ?")
	print ("Security patch: 0")	
	print (" ")
	print ("Windows XP")
	print ("Security level: ?")
	print ("Security patch: 0")	
	print (" ")
	print ("Windows Vista")
	print ("Security level: ?")
	print ("Security patch: 0")	
	print (" ")
	print ("Windows 7")
	print ("Security level: ?")
	print ("Security patch: 0")
	print (" ")
	print ("Windows 8x")
	print ("Security level: ?")
	print ("Security patch: 0")	
	print (" ")
	print ("Windows 10")
	print ("Security level: ?")
	print ("Security patch: 0")
	print (" ")
	print ("Windows MacOS")
	print ("Security level: ?")
	print ("Security patch: 0")
	print (" ")
	print ("Ubuntu")
	print ("Security level: ?")
	print ("Security patch: 0")	
	print (" ")
	print ("Other")
	print ("unmeasured")
	print (" ")
	print ("The command worked!")
	
print (in1)
testconfirm = int(input("Did the setup look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("System setup successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
    