in1 = str
print ("Command testing")
print ("Test the Update Info Beta command")
print ("Type 'UDINFBTA' to try out the command!")
print ("Warning! commands are CaSe SeNsItIvE!")
in1 = str(input("FC://"))
if in1 == ("UDINFBTA"):
	print ("==================================================================")
	print ("Update history for Beta versions")
	print ("==================================================================")
	print ("Version 1.0 Build 1")
	print ("Starting to build the program!")
	print ("Currently none of the programs or scripts work yet as python files, but we are gathering the required info, and building the kernel")
	print ("To start development")
	print ("Files:")
	print ("Test.py - This program is a beta of the systems interface through the OS kernel")
	print ("Source.txt - A copy of the source of the system, in plain text format")
	print ("Support.rtf - A Rich Text Format document telling you more info about rhe system, and its current plans")
	print ("BULIN1.txt - A code rip of a test of the operating system kernel. It doesn't work yet")
	print ("It doesn't have much to it, we didn't put much work into this version, we were just starting to lay the foundation for it")
	print ("File types used")
	print ("TXT - 2x")
	print ("PY - 1x")
	print ("RTF - 1x")
	print ("Directory count: 1")
	print ("Uncompressed update size: 58.8 KB (60,254 bytes)")
	print ("==================================================================")
	print ("Version 1.0.01 - Build 2")
	print ("Adding lots of work to the beginning of the system, a lot more functionality and features")
	print ("We have added a lot more files and info, and we have 2 command tests working, plus a setup test")
	print ("There is also slight documentation included, and a cool icon we made for the system")
	print ("Added new device codes and compatibility for Floppy, Cassette, DVD, and CD images")
	print ("Files")
	print ("Test.py - This program is a beta of the systems interface through the OS kernel")
	print ("Source.txt - A copy of the source of the system, in plain text format")
	print ("Support.rtf - A Rich Text Format document telling you more info about rhe system, and its current plans")
	print ("set up a connection.txt - A test of our info for our data service")
	print ("Setup.txt - A test of the setup programs code in plain text format")
	print ("Autonomous_system_(internet).pdf - Information about something we noticed our system could have been based on without knowing, but wasn't")
	print ("MEDOS differences with ASN.txt - A reply to the ASN argument, which was false, as we noticed our systems aren't related, and I was making up differences out of thin air")
	print ("Current concept.rtf - A rich text document about our current plans for our system")
	print ("Help command.py - A test of the help command")
	print ("COMPBLOG command.py - A test of the compatibility log command")
	print ("Logo.bmp - An extra image of the logo of our system")
	print ("MEDOS Build 2 vs. MS-DOS 10.png - A comparison of our system using the help command with MS-DOS 10 (Windows 10 command prompt)")
	print ("BUULIN1.txt - An extended code rip of a test of the operating system, based on the BULIN1 source code")
	print ("BULIN1.txt - A code rip of a test of the operating system kernel. It doesn't work yet")
	print ("Setuptest1.py - A test of the setup operation that doesn't work yet, either as setup, or preview")
	print ("Setuptest2.py - A test of the setup operation, that only works as a preview, and displays floppy disk insert info (legacy 1 only)")
	print ("HELP command.py - A copy of the help command in a different folder")
	print ("COMPBLOG command.py - A copy of the COMPBLOG command in a different folder")
	print ("HELP command.py - Another copy of the help command in a different folder")
	print ("COMPBLOG command.py - Another copy of the COMPBLOG command in a different folder")
	print ("OS Shell 1.0.py - A test of the operating system that is reprogrammed but still disfunctional")
	print ("Setuptest2.py - A copy of the setuptest2 file in a different folder")
	print ("We put a lot more work in this version, but went on to version 3, so we could archive the original")
	print ("File types used:")
	print ("PY - 11x")
	print ("TXT - 6x")
	print ("PDF - 1x")
	print ("PNG - 1x")
	print ("BMP - 1x")
	print ("Directory count: 10")
	print ("Uncompressed size: 460 KB (471,376 bytes)")
	print ("==================================================================")
	print ("Version 1.0.02 build 3")
	print ("No info available yet")
	print ("==================================================================")
	print ("The command worked!")
print (in1)
testconfirm = int(input("Did the command look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Command test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
    