in1 = str
print ("Command testing")
print ("Test the Android compatibility command")
print ("Type 'ANDRORUN' to try out the command!")
print ("Warning! Commands are CaSe SeNsItIvE")
in1 = str(input("FC:\\"))
if in1 == ("ANDRORUN"):
	print ("Android compatibility center")
	print ("0 Android 1.1")
	print ("1 Android 1.5")
	print ("2 Android 1.6")
	print ("3 Android 2.0")
	print ("4 Android 2.1")
	print ("5 Android 2.2")
	print ("6 Android 2.3")
	print ("7 Android 3.0")
	print ("8 Android 4.0")
	print ("9 Android 4.1")
	print ("A Android 4.4")
	print ("B Android 5.0")
	print ("C Android 5.1")
	print ("D Android 6.0")
	print ("E Android 6.1")
	print ("F Android 7.0")
	print ("G Android 7.1")
	print ("H Android 8.0")
	print ("I Android 8.1")
	print ("J Android 9.0")
	print ("K Android 9.1")
	print ("L Android 10.0")
	print ("Choose a number 0-9 or A-L then click enter to continue compatibility testing")
	print ("Type XE to quit")
	print (in1)
testconfirm = int(input("Did the command info look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
   