in1 = str
print ("Command testing")
print ("Test the Ubuntu compatibility command")
print ("Type 'UBURUN' to try out the command!")
print ("Warning! Commands are CaSe SeNsItIvE")
in1 = str(input("FC:\\"))
if in1 == ("UBURUN"):
	print ("Ubuntu compatibility center")
	print ("U1 Ubuntu 4.10")
	print ("U2 Ubuntu 5.04")
	print ("U3 Ubuntu 5.10")
	print ("U4 Ubuntu 6.04")
	print ("U5 Ubuntu 6.10")
	print ("U6 Ubuntu 7.04")
	print ("U7 Ubuntu 7.10")
	print ("U8 Ubuntu 8.04")
	print ("U9 Ubuntu 8.10")
	print ("D1 Ubuntu 9.04")
	print ("D2 Ubuntu 9.10")
	print ("D3 Ubuntu 10.04")
	print ("D4 Ubuntu 10.10")
	print ("D5 Ubuntu 11.04")
	print ("D6 Ubuntu 11.10")
	print ("D7 Ubuntu 12.04")
	print ("D8 Ubuntu 12.10")
	print ("D9 Ubuntu 13.04")
	print ("UD Ubuntu 13.10")
	print ("DU Ubuntu 14.04")
	print ("UD1 Ubuntu 14.10")
	print ("UD2 Ubuntu 15.04")
	print ("UD3 Ubuntu 15.10")
	print ("UD4 Ubuntu 16.04")
	print ("UD5 Ubuntu 16.10")
	print ("UD6 Ubuntu 17.04")
	print ("UD7 Ubuntu 17.10")
	print ("UD8 Ubuntu 18.04")
	print ("UD9 Ubuntu 18.10")
	print ("Type one of the given codes to change Ubuntu compatibility settings")
	print ("Type XE to quit")
	print (in1)
testconfirm = int(input("Did the command info look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
   