print ("Opening command: INTCOMP")
print ("Command type: Display info")
print ("Command size: 31138 bytes (30.4 Kilobytes)")
print ("Total lines of code used: 283")
print ("Command file format: .py (python file)")
print ("Location: Calculation Error!")
print ("This command shows you compatibility for the system integer architecture")
print ("Type 'INTCOMP' to try out command")
in1 = str(input("FC://"))
if in1 == ("INTCOMP"):
	print ("_____________________________________________")
	print ("|Compatibility log for MEDOS Integer testing|")
	print ("\===========================================/")
	print ("                                             ")
	print ("_______________________________________________________________________________________________________")
	print ("                  |                |                           |                                      |")
	print ("8 bit test        ()  16 bit test  () 32 bit test              () 64 bit test                         |")
	print ("                  |                |                           |                                      |")
	print ("Windows 1.0       | Windows 3.0    | Windows NT 3.1            | Windows XP 64 bit                    |")
	print ("Windows 1.01      | Windows 3.1    | Windows NT 3.5            | Windows Vista                        |")
	print ("Windows 1.02      | Windows 3.2    | Windows 95                | Windows Server 2008                  |")
	print ("Windows 1.03      |                | Windows NT 4              | Windows 7                            |")
	print ("Windows 1.04      | Mac System 4   | Windows 98                | Windows Server 2008 R2               |")
	print ("Windows 2.0       | Mac System 5   | Windows 98 Second Edition | Windows 8                            |")
	print ("Windows 2.01      | Mac System 6   | Windows ME                | Windows Server 2012                  |")                
	print ("Windows 2.02      |                | Windows 2000              | Windows 8.1                          |")
	print ("Windows 2.03      | PC-DOS 7.0     | Windows XP Starter        | Windows Server 2012 R2               |")
	print ("Windows 2.04      |                | Windows XP Home           | Windows 10                           |")
	print ("Windows 2.10      |                | Windows XP Professional   | Windows Server 2016                  |")
	print ("                  |                | Windows Server 2003       |                                      |")
	print ("Mac System 1      |                | Windows Vista             | Mac OS X 10.3                        |")
	print ("Mac System 2      |                | Windows Server 2003 R2    | Mac OS X 10.4                        |")
	print ("Mac System 3      |                | Windows Server 2008       | Mac OS X 10.5                        |")
	print ("                  |                | Windows 7                 | Mac OS X 10.6                        |")
	print ("PC-DOS 1.0        |                | Windows Server 2008 R2    | Mac OS X 10.7                        |")
	print ("PC-DOS 2.0        |                | Windows 8                 | OS X 10.8                            |")
	print ("PC-DOS 3.0        |                | Windows Server 2012       | OS X 10.9                            |")
	print ("PC-DOS 4.0        |                | Windows 8.1               | OS X 10.10                           |")
	print ("PC-DOS 5.0        |                | Windows Server 2012 R2    | OS X 10.11                           |")
	print ("PC-DOS 6.0        |                | Windows 10                | MacOS 10.12                          |")
	print ("PC-DOS 6.1        |                | Windows Server 2016       | MacOS 10.13                          |")
	print ("                  |                |                           | MacOS 10.14                          |")
	print ("                  |                | Mac System 7              |                                      |")
	print ("                  |                | Mac System 7.6            | Android 5.0                          |")
	print ("                  |                | Mac System 8              | Android 5.1                          |")
	print ("                  |                | Mac System 9              | Android 6.0                          |")
	print ("                  |                | Mac OS X                  | Android 6.1                          |")
	print ("                  |                | Mac OS X 10.1             | Android 7.0                          |")
	print ("                  |                | Mac OS X 10.2             | Android 7.1                          |")
	print ("                  |                | Mac OS X 10.3             | Android 8.0                          |")
	print ("                  |                | Mac OS X 10.4             | Android 8.1                          |")
	print ("                  |                | Mac OS X 10.5             | Android 9.0                          |")
	print ("                  |                | Mac OS X 10.6             |                                      |")
	print ("                  |                |                           | iOS 7                                |")
	print ("                  |                | Android 1.0               | iOS 8                                |")
	print ("                  |                | Android 1.1               | iOS 9                                |")
	print ("                  |                | Android 1.5               | iOS 10                               |")
	print ("                  |                | Android 1.6               | iOS 10.3                             |")
	print ("                  |                | Android 2.0               | iOS 11                               |")
	print ("                  |                | Android 2.1               | iOS 12                               |")
	print ("                  |                | Android 2.2               |                                      |")
	print ("                  |                | Android 2.3               | Ubuntu 12.04                         |")
	print ("                  |                | Android 3.0               | Ubuntu 12.10                         |")
	print ("                  |                | Android 3.1               | Ubuntu 13.04                         |")
	print ("                  |                | Android 4.0               | Ubuntu 13.10                         |")
	print ("                  |                | Android 4.1               | Ubuntu 14.04                         |")
	print ("                  |                | Android 4.4               | Ubuntu 14.10                         |")
	print ("                  |                | Android 5.0               | Ubuntu 15.04                         |")
	print ("                  |                | Android 5.1               | Ubuntu 15.10                         |")
	print ("                  |                | Android 6.0               | Ubuntu 16.04                         |")
	print ("                  |                | Android 6.1               | Ubuntu 16.10                         |")
	print ("                  |                | Android 7.0               | Ubuntu 17.04                         |")
	print ("                  |                | Android 7.1               | Ubuntu 17.10                         |")
	print ("                  |                | Android 8.0               | Ubuntu 18.04                         |")
	print ("                  |                | Android 8.1               | Ubuntu 18.10                         |")
	print ("                  |                |                           |                                      |")
	print ("                  |                | iPhone OS 1               | Solaris 7                            |")
	print ("                  |                | iPhone OS 2               | Solaris 8                            |")
	print ("                  |                | iPhone OS 3               | Solaris 9                            |")
	print ("                  |                |                           | Solaris 10                           |")
	print ("                  |                | iOS 4                     | Solaris 11                           |")
	print ("                  |                | iOS 5                     |                                      |")
	print ("                  |                | iOS 6                     |                                      |")
	print ("                  |                | iOS 7                     |                                      |")
	print ("                  |                | iOS 8                     |                                      |")
	print ("                  |                | iOS 9                     |                                      |")
	print ("                  |                | iOS 10                    |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                | Ubuntu 4.04               |                                      |")
	print ("                  |                | Ubuntu 4.10               |                                      |")
	print ("                  |                | Ubuntu 5.04               |                                      |") 
	print ("                  |                | Ubuntu 5.10               |                                      |")
	print ("                  |                | Ubuntu 6.04               |                                      |")
	print ("                  |                | Ubuntu 6.10               |                                      |")
	print ("                  |                | Ubuntu 7.04               |                                      |")
	print ("                  |                | Ubuntu 7.10               |                                      |")
	print ("                  |                | Ubuntu 8.04               |                                      |")
	print ("                  |                | Ubuntu 8.10               |                                      |")
	print ("                  |                | Ubuntu 9.04               |                                      |")
	print ("                  |                | Ubuntu 9.10               |                                      |")
	print ("                  |                | Ubuntu 10.4               |                                      |")
	print ("                  |                | Ubuntu 10.10              |                                      |")
	print ("                  |                | Ubuntu 11.04              |                                      |")
	print ("                  |                | Ubuntu 11.10              |                                      |")
	print ("                  |                | Ubuntu 12.04              |                                      |")
	print ("                  |                | Ubuntu 12.10              |                                      |")
	print ("                  |                | Ubuntu 13.04              |                                      |")
	print ("                  |                | Ubuntu 13.10              |                                      |")
	print ("                  |                | Ubuntu 14.04              |                                      |")
	print ("                  |                | Ubuntu 14.10              |                                      |")
	print ("                  |                | Ubuntu 15.04              |                                      |")
	print ("                  |                | Ubuntu 15.10              |                                      |")
	print ("                  |                | Ubuntu 16.04              |                                      |")
	print ("                  |                | Ubuntu 16.10              |                                      |")
	print ("                  |                | Ubuntu 17.04              |                                      |")
	print ("                  |                | Ubuntu 17.10              |                                      |")
	print ("                  |                | Ubuntu 18.04              |                                      |")
	print ("                  |                | Ubuntu 18.10              |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("                  |                |                           |                                      |")
	print ("=======================================================================================================")
	print ("Total entry slots: 8 bit = 256 | 16 bit = 256 | 32 bit = 256 | 64 bit = 256 | Total = 1024")
	print ("Used slots: unmeasured")
	print ("Available slots: unmeasured")
	print ("==========================================================================================================")
testconfirm = int(input("Did the command look right? Type a number, then click enter to exit"))
if testconfirm == 1:
    print ("Command test successful!")
    print ("Exiting...")
else:
    print ("Shutting down")
    