in1 = str
print ("Command testing")
print ("Test the keyboard test command")
print ("Type 'KBRDTEST' to try out the command!")
print ("Warning! Commands are CaSe SeNsItIvE")
in1 = str(input("FC://"))
if in1 == ("KBRDTEST"):
	print ("US Keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] | a |")
	print ("| A | b | B | c | C | d | D |")
	print ("| e | E | f | F | g | G | h |")
	print ("| H | i | I | j | J | k | K |")
	print ("| l | L | m | M | n | N | o |")
	print ("| O | p | P | q | Q | r | R |")
	print ("| s | S | t | T | u | U | v |")
	print ("| V | w | W | x | X | y | Y |")
	print ("| z |   |   |   |   |   | Z |")
	print ("Spanish keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |") 
	print ("French keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("German keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Russian keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Indonesian keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Swedish keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Chinese keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Japanese keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Korean keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("UK keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Zulu keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Greek keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Mandarin keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Roman keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Dutch keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Arabic keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Danish keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Italian keyboard")
	print ("| 0 | 1 | 2 | 3 | 4 | 5 | 6 |")
	print ("| 7 | 8 | 9 | # | . | , | > |")
	print ("| < | ? | / | \ | | | : | ; |")
	print ("| [ | ' | - | _ | = | + | ~ |")
	print ("| ` | ! | @ | $ | % | ^ | & |")
	print ("| * | ( | ) | { | } | ] |   |")
	print ("|   |   |   |   |   |   |   |")
	print ("Unicode keyboard")
	print ("|   |   |   |   |   |   |   |")
	print (in1)
testconfirm = int(input("Did the command info look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")