in1 = str
print ("Command testing")
print ("Opening command: UDINFBTA")
print ("Command type: Beta Information log")
print ("Command size: 13999 bytes (13.60 Kilobytes)")
print ("Total lines of code used: 192")
print ("Command file format: .py (python file)")
print ("Location: Calculation Error!")
print ("Test the system crash command")
print ("Test the Update Info Beta command")
print ("Type 'UDINFBTA' to try out the command!")
print ("Warning! commands are CaSe SeNsItIvE!")
in1 = str(input("FC://"))
if in1 == ("UDINFBTA"):
	print ("==================================================================")
	print ("Update history for Beta versions")
	print ("==================================================================")
	print ("Version 1.0 Build 1")
	print ("Starting to build the program!")
	print ("Currently none of the programs or scripts work yet as python files, but we are gathering the required info, and building the kernel")
	print ("To start development")
	print ("Files:")
	print ("Test.py - This program is a beta of the systems interface through the OS kernel")
	print ("Source.txt - A copy of the source of the system, in plain text format")
	print ("Support.rtf - A Rich Text Format document telling you more info about rhe system, and its current plans")
	print ("BULIN1.txt - A code rip of a test of the operating system kernel. It doesn't work yet")
	print ("It doesn't have much to it, we didn't put much work into this version, we were just starting to lay the foundation for it")
	print ("File types used")
	print ("TXT - 2x")
	print ("PY - 1x")
	print ("RTF - 1x")
	print ("Directory count: 1")
	print ("Uncompressed update size: 58.8 KB (60,254 bytes)")
	print ("==================================================================")
	print ("Version 1.0.01 - Build 2")
	print ("Adding lots of work to the beginning of the system, a lot more functionality and features")
	print ("We have added a lot more files and info, and we have 2 command tests working, plus a setup test")
	print ("There is also slight documentation included, and a cool icon we made for the system")
	print ("Added new device codes and compatibility for Floppy, Cassette, DVD, and CD images")
	print ("Files")
	print ("Test.py - This program is a beta of the systems interface through the OS kernel")
	print ("Source.txt - A copy of the source of the system, in plain text format")
	print ("Support.rtf - A Rich Text Format document telling you more info about rhe system, and its current plans")
	print ("set up a connection.txt - A test of our info for our data service")
	print ("Setup.txt - A test of the setup programs code in plain text format")
	print ("Autonomous_system_(internet).pdf - Information about something we noticed our system could have been based on without knowing, but wasn't")
	print ("MEDOS differences with ASN.txt - A reply to the ASN argument, which was false, as we noticed our systems aren't related, and I was making up differences out of thin air")
	print ("Current concept.rtf - A rich text document about our current plans for our system")
	print ("Help command.py - A test of the help command")
	print ("COMPBLOG command.py - A test of the compatibility log command")
	print ("Logo.bmp - An extra image of the logo of our system")
	print ("MEDOS Build 2 vs. MS-DOS 10.png - A comparison of our system using the help command with MS-DOS 10 (Windows 10 command prompt)")
	print ("BUULIN1.txt - An extended code rip of a test of the operating system, based on the BULIN1 source code")
	print ("BULIN1.txt - A code rip of a test of the operating system kernel. It doesn't work yet")
	print ("Setuptest1.py - A test of the setup operation that doesn't work yet, either as setup, or preview")
	print ("Setuptest2.py - A test of the setup operation, that only works as a preview, and displays floppy disk insert info (legacy 1 only)")
	print ("HELP command.py - A copy of the help command in a different folder")
	print ("COMPBLOG command.py - A copy of the COMPBLOG command in a different folder")
	print ("HELP command.py - Another copy of the help command in a different folder")
	print ("COMPBLOG command.py - Another copy of the COMPBLOG command in a different folder")
	print ("OS Shell 1.0.py - A test of the operating system that is reprogrammed but still disfunctional")
	print ("Setuptest2.py - A copy of the setuptest2 file in a different folder")
	print ("We put a lot more work in this version, but went on to version 3, so we could archive the original")
	print ("File types used:")
	print ("PY - 11x")
	print ("TXT - 6x")
	print ("PDF - 1x")
	print ("PNG - 1x")
	print ("BMP - 1x")
	print ("Directory count: 10")
	print ("Uncompressed size: 460 KB (471,376 bytes)")
	print ("==================================================================")
	print ("Version 1.0.02 build 3A")
	print ("HUGE UPDATE")
	print ("20+ New commands")
	print ("New working commands including:")
	print ("DIR = Directory viewing")
	print ("BCHECK = Learn more about computer memory")
	print ("KBRDTEST = Test your keyboard")
	print ("3.RUN = Test compatibility for Windows 3.0, 3.1, 3.2, and 3.5 devices")
	print ("ANDRORUN = Test compatibility for Android devices")
	print ("CALC = Test a calculator")
	print ("IORUN = Test compatibility for iOS devices")
	print ("MASYSRUN = Test compatibility for classic macOS devices")
	print ("SECURINF = See security info for the system")
	print ("TASKMAN = Task management, see all the processes on your system (early beta, not fully functional")
	print ("V7RUN = Test the compatibility for Windows Server 2008, Windows Vista, and Windows 7 devices")
	print ("9XRUN = Test the compatibility for Windows 9x devices")
	print ("BGUIDE = Disk memory help guide, learn more about computer storage")
	print ("CD = Test Compact Disk images")
	print ("CRED = View the credits for the operating system")
	print ("KRBDTEST = Test your keyboard")
	print ("INTCOMP = Test integer compatibility")
	print ("MCXRUN = Test compatibility for Mac OS X, OS X, and MacOS devices")
	print ("SYSCRASH%7 = Test your systems stability and error logs with a manual crash (it is just a test, it won't crash your system for real)")
	print ("UBURUN = Test compatibility for Ubuntu devices")
	print ("XPRUN = Test compatibility for Windows XP and Server 2003 devices")
	print ("8BITTEST1X = Test your system and make it count to an 8 bit integer, 1 number at a time")
	print ("16BITTEST1X = Test your system and make it count to an 16 bit integer, 1 number at a time")
	print ("32BITTEST1X = Test your system and make it count to an 32 bit integer, 1 number at a time")
	print ("64BITTEST1X = Test your system and make it count to an 64 bit integer, 1 number at a time")
	print ("64BITTEST1000X = Test your system and make it count to an 64 bit integer, but not reach an exact point, and keep going until you crash, 000 numbers at a time")
	print ("INTCOMP (for debugging) = View system compatibiliy for integer testing")
	print ("DOSTOP = A huge feature! A Terminal Desktop (TD) or Command Line Desktop (CMD) That is a desktop similar to Windows 95, or Openlinux 2.5. A little easter egg, the time is always set to 3:55 pm, since we started our business at that exact time")
	print ("Cleaned up and organized all directories")
	print ("Files")
	print ("Test.py - This program is a beta of the systems interface through the OS kernel")
	print ("Source.txt - A copy of the source of the system, in plain text format")
	print ("Support.rtf - A Rich Text Format document telling you more info about rhe system, and its current plans")
	print ("set up a connection.txt - A test of our info for our data service")
	print ("Setup.txt - A test of the setup programs code in plain text format")
	print ("Autonomous_system_(internet).pdf - Information about something we noticed our system could have been based on without knowing, but wasn't")
	print ("MEDOS differences with ASN.txt - A reply to the ASN argument, which was false, as we noticed our systems aren't related, and I was making up differences out of thin air")
	print ("Current concept.rtf - A rich text document about our current plans for our system")
	print ("Help command.py - A test of the help command")
	print ("COMPBLOG command.py - A test of the compatibility log command")
	print ("Logo.bmp - An extra image of the logo of our system")
	print ("MEDOS Build 2 vs. MS-DOS 10.png - A comparison of our system using the help command with MS-DOS 10 (Windows 10 command prompt)")
	print ("BUULIN1.txt - An extended code rip of a test of the operating system, based on the BULIN1 source code")
	print ("BULIN1.txt - A code rip of a test of the operating system kernel. It doesn't work yet")
	print ("Setuptest1.py - A test of the setup operation that doesn't work yet, either as setup, or preview")
	print ("Setuptest2.py - A test of the setup operation, that only works as a preview, and displays floppy disk insert info (legacy 1 only)")
	print ("HELP command.py - A copy of the help command in a different folder")
	print ("COMPBLOG command.py - A copy of the COMPBLOG command in a different folder")
	print ("HELP command.py - Another copy of the help command in a different folder")
	print ("COMPBLOG command.py - Another copy of the COMPBLOG command in a different folder")
	print ("OS Shell 1.0.py - A test of the operating system that is reprogrammed but still disfunctional")
	print ("Setuptest2.py - A copy of the setuptest2 file in a different folder")
	print ("DIRSORT.ini - A dummy initiative file for future use")
	print ("BGUIDE command.py - The command testing file to test the memory guide program")
	print ("KBRDTEST command.py - The command testing file to test the keyboard testing program")
	print ("DIR command.py - The command testing file to test the directory viewing program")
	print ("UDINFBTA command old.py - The abandoned version of the update info beta program for this build")
	print ("UDINFBTA command.py - The test program to show you the info for the update development of the beta version of this program")
	print ("We put a lot more work in this version, but went on to version 3, so we could archive the original")
	print ("File types used (older):")
	print ("PY - 17x")
	print ("TXT - 6x")
	print ("PDF - 1x")
	print ("RTF - 2x")
	print ("PNG - 1x")
	print ("BMP - 1x")
	print ("INI - 1x")
	print ("Directory count: 40")
	print ("Another new feature was added: Command Line Screensavers!")
	print ("These screensavers are completely made up of ASCII art, and loop until the user stops them")
	print ("Unfortunately, they aren't that advanced yet, you can't stop them without exiting the system")
	print ("But they work correctly")
	print ("We included 3 screensavers in this build:")
	print ("Platformers sky")
	print ("Pinefall")
	print ("7 nation army binary")
	print (" ")
	print ("A new piece of data is slowly being added to the top of commands to tell more about them. You will notice")
	print ("The new header at the top of this command")
	print ("Brand new audio system, that unfortunately takes up over 75x more than the actual system")
	print ("We included a 3 track audio directory, with 3 new system sounds:")
	print ("_________________________________________________________________________________________________")
	print ("|#1 Startup sound.wav by MEDOS System | This is the new startup sound for the operating system  |")
	print ("|This sound is a mixture of: | It is fair use, and might be changed in the future               |")
	print ("|Windows 98 startup sound, Old Ubuntu Startup sound, a MacOS Startup remix, and a stephen       |")
	print ("|Hawking voice saying: 'welcome'                                                                |")
	print ("=================================================================================================")
	print ("|#2 Shutdown sound.wav by MEDOS System | This is the new shutdown sound for the operating system|")
	print ("|This sound is a mixture of: | It is fair use, and might be changed in the future               |")
	print ("|Windows NT 5 shutdown sound, Old Ubuntu shutdown sound, a MacOS 1994 remix, and a stephen      |")
	print ("|Hawking voice saying: 'goodbye user'                                                           |")
	print ("=================================================================================================")
	print ("|#3 Connecting to receiver.wav by MEDOS System | This is a connection sound for the operating   |")
	print ("|system that plays when you are connecting to the receiver device, or have a poor connection. It|")
	print ("|Is a modified version of the AOL dialup sound, without the dialing up                          |")
	print ("=================================================================================================")
	print (" ")
	print ("New media was added for the DOSTOP, a picture of it was added to the extras folder")
	print ("This is the A version of build 3. The B version is the same, except it doesn't have the audio files")
	print ("Built-in, so it is a smaller, and more compressed size")
	print (" ")
	print ("Uncompressed size: ***.**")
	print ("==================================================================")
	print ("Version 1.0.02 build 3B")
	print ("This is a modified version of Build 3A, just without the audio files, which reduces the system size by")
	print ("50 Megabytes, and makes the system under 700 kilobytes again")
	print ("==================================================================")
	print ("The command worked!")
print (in1)
testconfirm = int(input("Did the command look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Command test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
    