in1 = str
print ("Command testing")
print ("Test the Windows Aero (Vista and 7) compatibility command")
print ("Type 'V7RUN' to try out the command!")
print ("Warning! Commands are CaSe SeNsItIvE")
in1 = str(input("FC:\\"))
if in1 == ("V7RUN"):
	print ("Windows Vista/Windows 7 compatibility center")
	print ("A Windows Vista no service pack")
	print ("B Windows Vista service pack 1")
	print ("C Windows Vista Service pack 2")
	print ("D Windows 7 No service pack")
	print ("E Wndows 7 Service pack 1")
	print ("F Windows Server 2008")
	print ("G Windows Server 2008 R2")
	print ("H Windows Longhorn")
	print ("I Windows Blackcomb")
	print ("0 Home edition")
	print ("1 Home Premium")
	print ("2 Business edition")
	print ("3 Ultimate edition")
	print ("4 Starter edition")
	print ("5 Enterprise edition")
	print ("6 Professional edition")
	print ("Choose a letter A-I followed by a number 0-6 then click enter to continue compatibility testing")
	print ("Type XE to quit")
	print (in1)
testconfirm = int(input("Did the command info look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
   