in1 = str
print ("Command testing")
print ("Test the disk memory help guide command")
print ("Type 'BGUIDE' to try out the command!")
print ("Warning! Commands are CaSe SeNsItIvE")
in1 = str(input("FC://"))
if in1 == ("BGUIDE"):
	print ("Welcome to the memory guide!")
	print ("Learn more about computer storage here")
	print ("-----")
	print ("Memory size")
	print ("Byte = 8 bits")
	print ("Kilobyte = 1024 bytes")
	print ("Megabyte = 1024 Kilobytes")
	print ("Gigabyte = 1024 Megabytes")
	print ("Terabyte = 1024 Gigabytes")
	print ("Petabyte = 1024 Terabytes (this system is incapable of holding petabytes of memory)")
	print ("Exabyte = 1024 Petabytes (this system is incapable of holding exabytes of memory)")
	print ("Zettabyte = 1024 Exabytes (this system is incapable of holding zettabytes of memory)")
	print ("Yottabyte = 1024 Zettabytes (this system is incapable of holding yottabytes of memory")
	print ("-----")
	print ("Internet Speed (upload and download)")
	print ("Kilobit connection = 125 bytes per second")
	print ("Megabit connection = 125 Kilobits per second")
	print ("Gigabit connection = 125 Megabits per second")
	print ("Terabit connection = 125 Gigabits per second (this system is incapable of reaching that speed)")
	print ("Petabit connection = 125 Terabits per second (this system is incapable of reaching that speed)")
	print ("Exabit connection = 125 Petabits per second (this systrem is incapable of reaching that speed)")
	print ("Zettabit connection = 125 Exabits per second (this system is incapable of reaching that speed)")
	print ("Yottabit connection = 125 Zettabits per second (this system is incapable of reaching that speed)")
	print ("-----")
	print ("Integers of memory size")
	print ("Byte = 1 Squared 8 bits")
	print ("Kilobyte = 2 Squared 10 bytes")
	print ("Megabyte = 2 Squared 20 bytes")
	print ("Gigabyte = 2 Squared 30 bytes")
	print ("Terabyte = 2 Squared 40 bytes")
	print ("Petabyte = 2 Squared 50 bytes")
	print ("Exabyte = 10 Squared 18 bytes")
	print ("Zettabyte = 10 Squared 21 bytes")
	print ("Yottabyte = 10 Squared 24 bytes")
	print ("-----")
	print ("Working with memory")
	print ("A computer works with memory in many ways such as:")
	print ("Read speed")
	print ("Write speed")
	print ("Download speed")
	print ("Upload speed")
	print ("Connection speed")
	print ("CPU speed")
	print ("Disk speed")
	print ("GPU speed")
	print ("Network speed")
	print ("Utilization speed")
	print ("Cache speed")
	print ("Clock speed")
	print ("Pool speed")
	print ("Response speed")
	print ("Send speed")
	print ("Receive speed")
	print ("Decode speed")
	print ("Execute speed")
	print ("Processor speed")
	print ("Processing speed")
	print ("Loading speed")
	print ("Packets")
	print ("Transfer")
	print ("Processes")
	print ("Threads")
	print ("Handles")
	print (in1)
testconfirm = int(input("Did the command info look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
   