in1 = str
print ("Command testing")
print ("Opening command: CMNDTEST")
print ("Command type: Command Testing Center Testing")
print ("Command size: 4654 bytes (4.54 Kilobytes)")
print ("Total lines of code used: 67")
print ("Command file format: .py (python file)")
print ("Location: Calculation Error!")
print ("Test the Command Testing command (inception)")
print ("Type 'CMNDTEST' to try out the command!")
print ("Warning! Commands are CaSe SeNsItIvE")
in1 = str(input("FC://"))
if in1 == ("CMNDTEST"):
	print ("========================================================================================================================================")
	print ("| Welcome to the command testing area!                                                                                                 |")
	print ("| Here, you can learn about commands, or test them in a safer environment without modifying your system                                |")
	print ("| To start, look for a command, then type it in to test it                                                                             |")
	print ("| To exit command testing, press one of the following keys: | ESC | ALT | COMMAND | FN | CTRL | TAB | DEL |                            |")
	print ("| Select a command from below to begin:                                                                                                |")
	print ("|                                                                                                                                      |")
	print ("| Beginner                                                                                                                             |")
	print ("| DEL | RENAME | CD | COMPBLOG | PREVTOG | USRDOC | UDINFBTA | BGUIDE | KBRDTEST | HELP | DOSTOP | SYSFAQ | CLS | EXIT | AUD# | REFRESH|")
	print ("| PLAY | CALC | EJECT | FLOPDEVI | DISCON | SPCHK | 9XRUN | XPRUN |3.RUN | MASYSRUN | MCXRUN | UBURUN | V7RUN | IORUN | ANDRORUN |     |")
	print ("| PINEFALL | DNAFARM | 7NATIONARMYBINARY | PLATFORMERSSKY | 																		   |")
	print ("| 																																	   |")
	print ("| Intermediate																														   |")
	print ("| RUN | CD| TLDINF | COLOR | SYSSETS | UPDUSR2 | NETW | USR2 | INTCOMP | 8BITEST1X | 16BITEST1X | 32BITEST1X | 64BITEST1X|64BITEST1000X|")
	print ("| SYSCRASH%7 |                                                                                                                         |")
	print ("|																																	   |")
	print ("| Advanced  																														   |")
	print ("| TASKMAN | FORMAT | FLOPSRCH | MOUNT | PNP | DRCHECK | VMOUTRUN | VMORUTOG |   													   |")
	print ("| Expert                                                                                                                               |")
	print ("| PYCON | SRCVIEW |   																												   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("|																																	   |")
	print ("========================================================================================================================================")
	print (in1)
testconfirm = int(input("Did the command info look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
   