in1 = str
print ("Command testing")
print ("Test the compatibility log command")
print ("Type 'COMPBLOG' to try out the command!")
print ("Warning! Commands are CaSe SeNsItIvE")
in1 = str(input("FC://"))
if in1 == ("COMPBLOG"):
	print ("File compatibility for MEDOS HDD")
	print ("Documents")
	print ("| RTF |  TXT   |   XPS   |   ODS   |   ODX  | PDF | DOCX   |  HTML   |  HTM   |")
	print ("Images")
	print ("| BMP | DMP | PNG | JPEG | JPE | JFIF | GIF | TIF | TIFF | SVG |")
	print ("| GIF_C200 | PSD | ICO | ICN | PNS |") 
	print ("Videos")
	print ("| MP4 | AVI | WMV | 3GP | WEBM | WLMP | WMMP | MOV | M4V | MKV|")
	print ("| AVC | MPEG-4 | SWF | FLV | FLA | VOB | OGV | DRC | GIFV | MNG |")
	print ("| QT | YUV | RM | RMVB | ASF | AMV | M4P |")
	print ("Music")
	print ("| OGG | MP3 | MID | FLAC | WAV | AA | AAC | AAX | AMR | APE |")
	print ("| AU | M4B | RAW | VOX | WMA |")
	print ("System")
	print ("| SYS | PY | BAT | DAT | INI | SLN | EXE | INF | 0 | BIN |")
	print ("| LOCK | 1 | 2 | 3 |")
	print ("Media")
	print ("| IMG | IMAGE | ISO | ZIP | 7Z | TAR | RAR | XZ | ISO | DMG |")
	print ("| URL | INK | TORRENT |")
	print (in1)
testconfirm = int(input("Did the command info look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
   