in1 = str
print ("Command testing")
print ("Opening command: SYSSETS")
print ("Command type: System Setting Modification (safe)")
print ("Command size: 9074 bytes (8.86 Kilobytes)")
print ("Total lines of code used: 152")
print ("Command file format: .py (python file)")
print ("Location: Calculation Error!")
print ("Test the system settings command")
print ("Type 'SYSSETS' to try out the command!")
print ("Warning! Commands are CaSe SeNsItIvE")
in1 = str(input("FC://"))
if in1 == ("SYSSETS"):
	print (" ")
	print (" ")
	print ("===================================================")
	print ("MEDOS System Settings Console                      ")
	print ("Version 1.0)                                       ")
	print ("===================================================")
	print ("|                   Display                       |")
	print ("===================================================")
	print ("___________________________________________________")
	print ("| Resolution | 144p | 240p | 288p | 360p | < 480p |")
	print ("| 540p | 720p | 1080p | 1440p | 2160p [4K] ||||||||")
	print ("| 4320p [8K] | 8640p | [16K] ||||||||||||||||||||||")
	print ("===================================================")
	print ("| Aspect Ratio                                    |")
	print ("| 1x1 |   3x2   |    3x3  |     4x2   |    4x4    |")
	print ("| 0 1 | 0 1 2 3 | 0 1 2 3 | 0 1 2 3 4 | 0 1 2 3 4 |")
	print ("| 1 * | 1 * * * | 1 * * * | 1 * * * * | 1 * * * * |")
	print ("||||||| 2 * * * | 2 * * * | 2 * * * * | 2 * * * * |")
	print ("||||||||||||||||| 3 * * * ||||||||||||| 3 * * * * |")
	print ("||||||||||||||||||||||||||||||||||||||| 4 * * * * |")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("|    5x3     |     5x5     |      6x3      ||||||||")
	print ("|0 1 2 3 4 5 | 0 1 2 3 4 5 | 0 1 2 3 4 5 6 ||||||||")
	print ("|1 * * * * * | 1 * * * * * | 1 * * * * * * ||||||||")
	print ("|2 * * * * * | 2 * * * * * | 2 * * * * * * ||||||||")
	print ("|3 * * * * * | 3 * * * * * | 3 * * * * * * ||||||||")
	print ("|||||||||||||| 4 * * * * * | 4 * * * * * * ||||||||")
	print ("|||||||||||||| 5 * * * * * | 5 * * * * * * ||||||||")
	print ("|||||||||||||||||||||||||||| 6 * * * * * * ||||||||")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("|       7x4       |        7x7      |||||||||||||||") 
	print ("| 0 1 2 3 4 5 6 7 | 0 1 2 3 4 5 6 7 |||||||||||||||")
	print ("| 1 * * * * * * * | 1 * * * * * * * |||||||||||||||")
	print ("| 2 * * * * * * * | 2 * * * * * * * |||||||||||||||")
	print ("| 3 * * * * * * * | 3 * * * * * * * |||||||||||||||")
	print ("| 4 * * * * * * * | 4 * * * * * * * |||||||||||||||")
	print ("||||||||||||||||||| 5 * * * * * * * |||||||||||||||")
	print ("||||||||||||||||||| 6 * * * * * * * |||||||||||||||")
	print ("||||||||||||||||||| 7 * * * * * * * |||||||||||||||")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("|        8x5        |        8x8        |||||||||||")
	print ("| 0 1 2 3 4 5 6 7 8 | 0 1 2 3 4 5 6 7 8 |||||||||||")
	print ("| 1 * * * * * * * * | 1 * * * * * * * * |||||||||||")
	print ("| 2 * * * * * * * * | 2 * * * * * * * * |||||||||||")
	print ("| 3 * * * * * * * * | 3 * * * * * * * * |||||||||||")
	print ("| 4 * * * * * * * * | 4 * * * * * * * * |||||||||||")
	print ("| 5 * * * * * * * * | 5 * * * * * * * * |||||||||||")
	print ("||||||||||||||||||||| 6 * * * * * * * * |||||||||||")
	print ("||||||||||||||||||||| 7 * * * * * * * * |||||||||||")
	print ("||||||||||||||||||||| 8 * * * * * * * * |||||||||||")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("| Font size | 8 | 10 > | 12 | 14 | 16 | 18 | 20 |||")
	print ("| 22 | 24 | 26 | 28 | 30 | 32 | 34 | 36 | 38 | 40 |")
	print ("| 42 | 44 | 46 | 48 | 50 | 52 | 54 | 56 | 58 | 60 |")
	print ("| 62 | 64 | 66 | 68 | 70 | 72 | 74 | 75 |||||||||||")
	print ("| changing the font size does not effect the      |")
	print ("| DOSTOP command                                  |")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("| Font style                                      |")
	print ("| Arial | Courier > | Calibri | Comic Sans MS |||||")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("| Color mode                                      |")
	print ("| Black & White > | Greyscale | 16 Color ||||||||||")
	print ("| 256 color | 24 Bit color ||||||||||||||||||||||||")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("|              System Compatibility               |")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("| System Integer | 4 bit | 8 bit | 12 bit | 16 bit|")
	print ("| 24 bit | 32 bit > | 48 bit | 64 bit | 128 bit |||")
	print ("| 256 bit | 512 bit |||||||||||||||||||||||||||||||")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("|Compatibility Mode: Windows XP, Windows Vista,   |")
	print ("| Windows 7, Windows 8, Windows 8.1, Windows 10   |")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("| System Language | Assembly | BASIC | C | C+ |||||")
	print ("| Python 1.6 | Python 2 | Python 2.7 | Python 3 |||")
	print ("| Python 3.2 | Python 3.6 > | Python ? ||||||||||||")
	print ("|Device Type| Floppy disk 360K | Floppy disk 720K||")
	print ("| Floppy disk 1.2M | Floppy disk 1.44M ||||||||||||")
	print ("| Cassette C60 | Cassette C90 | CD legacy 1 |||||||")
	print ("| CD Legacy 2 | CD Legacy 3 | CD Legacy 4 |||||||||")
	print ("| DVD Legacy 1 | DVD Legacy 2 | DVD Legacy 3 ||||||")
	print ("| DVD Legacy 4 | USB 1.0 | USB 2.0 | USB 3.0 ||||||")
	print ("| USB 3.1 | SD Legacy1 | SD Legacy2 | SD Legacy3|||")
	print ("| SD Legacy4 | HDD Legacy 1 | HDD Legacy 2 ||||||||")
	print ("| HDD Legacy 3 > | HDD Legacy 4 |||||||||||||||||||")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("| File compatibility:                             |")
	print ("| Storage only | Store/open |||||||||||||||||||||||")
	print ("|  PDF | XPS   | TXT | RTF ||||||||||||||||||||||||")
	print ("| BMP  | JPEG  | HTML| PY  ||||||||||||||||||||||||")
	print ("| JPE  | JFIF  | HTM |     ||||||||||||||||||||||||")
	print ("| GIF  | ODX   |     |     ||||||||||||||||||||||||")
	print ("| ODS  | DMP   |     |     ||||||||||||||||||||||||")
	print ("| PNG  | GIF_C200 |     |       |||||||||||||||||||")
	print ("| PSD  | ICO   |      |     |||||||||||||||||||||||")
	print ("| ICN  | PNS   |      |     |||||||||||||||||||||||")
	print ("| MP4  | AVI   |      |     |||||||||||||||||||||||")
	print ("| WMV  | 3GP   |      |     |||||||||||||||||||||||")
	print ("| WEBM | WLMP  |      |     |||||||||||||||||||||||")
	print ("| WMMP | MOV   |      |     |||||||||||||||||||||||")
	print ("| M4V  | MKV   |      |     |||||||||||||||||||||||")
	print ("| MRV  | AVC   |      |     |||||||||||||||||||||||")
	print ("| MPEG4| SWF   |      |     |||||||||||||||||||||||")
	print ("| FLV  | FLA   |      |     |||||||||||||||||||||||")
	print ("| VOB  | OGV   |      |     |||||||||||||||||||||||")
	print ("| GIFV | DRC   |      |     |||||||||||||||||||||||")
	print ("| MNG  | QT    |      |     |||||||||||||||||||||||")
	print ("| YUV  | RM    |      |     |||||||||||||||||||||||")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("| System security level: 0 (Not Network Capable) ||")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("|                 Performance                     |")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("| Read speed: # KB/S MB/S GB/S                    |")
	print ("| Write speed: # KB/S MB/S GB/S                   |")
	print ("| Transfer speed: # KB/S MB/S GB/S                |")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("| Performance Mode | Standard | Adjusted > ||||||||")
	print ("| High performance | Ultra performance | Max ||||||")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("|                 Connection                      |")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("| Read speed: # KB/S MB/S GB/S                    |")
	print ("| Write speed: # KB/S MB/S GB/S                   |")
	print ("| Transfer speed: # KB/S MB/S GB/S                |")
	print ("| Connection speed: # B/S KB/S MB/S GB/S          |")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("| Connection type | Dialup | DSL | Wi-Fi ||||||||||")
	print ("| Bluetooth | 1x | 3G | 4G | 5G | Mobile Hotspot ||")
	print ("|||||||||||||||||||||||||||||||||||||||||||||||||||")
	print ("| Webconnect | HTTPS | HTTP | HTTPS & HTTP > ||||||")
	print ("| None | WWW | All |||||||||||||||||||||||||||||||||")
	print (in1)
testconfirm = int(input("Did the command info look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
   