print ("Wallpaper previews.py")
print ("=====================")
print ("Wallpaper: Blisscii 150x | Size: 9.05 KB | Based on: Windows XP Bliss")
print (" ")
print ("/+/ooooo+/000+oooo++++++oooooooooooooo+++++++0--...```-//00---.---0000/+++oooooo++++/////////00////+ooo+-`````````````````..``````````````````````````")
print ("````-o++++0-.-0+++/-...-/ooooooooooooooooo+o+++//0.```.0/0000--..----000/++++ooooo++/00//+++oooo++osyyso/.````````````````.--.```````````````````.....")
print ("`````.-.`.--.----.--.````-+oo+//+oooo++oooooo+++++//0000//////00-------000////+++++++//0/+ooossyysysyyyys+0-..-0--....-..------.......`````````.......")
print ("00-00/+0```````.-.`.```````0/+///ooo+oooooooooooooo+++++++++++////0-----0000///////++++///+osssyyyyyyyssso++/+ooo+0-0000//////--................``````")
print ("+++++ooo/0-``.`.-0---...```.-0////+o+o+o+ooooooooooooooo++++++++////00------00000000/+++++++oosyyyyyyyyso/0+syyyyso++ooosssss+-..........------..`````")
print ("oooooo++o+//00..-00///00/-----0//+o+o+///ooooooooooooooooooo++++++++////000---------00/++oooo+ossyyyyyyyysooyyyyyyssooooo+//+/--.```.```0+/0--...`````")
print ("ooooooooooooo///+o++++0/++oo+//+oooooooooooooosoooooooooooooooo++++++///////00000----00//+ooooooosyyyyyyyyyyyyyyyyyyssso/0-0/0-..```````-/+-.`````````")
print ("ooooooooooooooooooooooooooooooooooooossssssssssssssooooooooooooooo++++///////////00--00//+++oosooosyyyyyyysyyyyyyyyyysoo+////0...........--.``````````")
print ("ooooooooooooooooooooooooooooooooossossssssssssssssssssssooooooooooooo+////0/////////0-0///+oooosssssssyyyysssyyyyyyyysso+/---.....-/+/0000--..........")
print ("++ooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssooooooo+++////00000/++/////++ossssssssssyyyyyyyyyyyyyyyssso/0------00/++++///+////++//+")
print ("+++++++oooooooooooooooooooooooooooooooooosssssssssssssssssssssssssooooooo+++///000//++o+++++oossssssssyysssyyyyyyyyyyyyyyyssoo+00000+oooosssssssssssss")
print ("++++++++++oooooooooooooooooooooooooooooooooossssssssssssssssssssssssssooooo++//000000//+oooooossssssyyyyyyyyyyyyyyyyyyyyyyyyssssooossossyyssyyyyyyyssy")
print ("++++++++++++++++++oooooooooooooooooooooooooooooossssssssssssssssssssssssssoooo++///00////++ooosssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyysyssssysyyyyyyyysssoo")
print ("+++++++++++++++++++++++oooooooooooooooooooooooooooooosssssssssssssssssssssssssssoooo++/////+oosssssssssssssssyyyyyyyyyyyyyyyyyyyssssssssssssssssssso++")
print ("+++++++++++++++++++++++++++oo+++/+/0/+ooo++/--+ooooooooooossssssssssssssssssssssssoooooo++//++osssssssssssssssssssssssssssssssssssssssoossssssssossoo+")
print ("+++++++++++++++++++++++++++++++/--..--/++/0--.-+ooooooooooooooosssssssssssssssooooooooooooooooooosssssssssssssssssssssssssssssssssssoo++o+0/0/00/+oooo")
print ("++++++++++++++++++++++++++++++++++++++++ooo++///++ooooooooooooooooossssssssssoooooooooosssssssssssssssssssssssssssssssssssssssssssssssoo/0-...-0-..-/+")
print ("/////++++++++//++++/+++++++++++++++++/++++oooooo++++ooooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssssssssssssssooo+0..--////00--.")
print ("////////////++++++++++++++++++++++++///+++++++++++++ooooooooooooooooooooooooooooooooo+oooossssssssssssssssso+//++/+osssssssssssssssssso+/0//0/+++++//0")
print ("//////////////////////+++++++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooossssssssss+-````````-/0+osssssssssssssso+++ooooosooooo")
print ("/////////////00-------00///////++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooooooooooooooooo+/0.```````...--0+oossssssssssssssssssoooooooo")
print ("///////////////00--.````....--0///++++++++++++++++++++++++++++++++///+++++++++++ooooooooooooooooooooo++/-..--....-0//00000/+oooooooooooooooooooooooooo")
print ("00///////////////0000-.```````.-0/////+++++++++++++++++++++++++++/000-..``````.-/+++++++++ooooooooooo++++/+o+////0//+////00/+oooooooooooooooooo+/00/+o")
print ("000000000//////////000--..`...--00//////////++++++++++++//++++++++/00-.`````````.//+++++++oooooooo+0--//++++0..`.```````..--.----/+++++++++++++++++++/")
print ("00000000000000/////////000----0000//////////////+++++++++/+++++++++//0-`````````.000/////++++++++/.```-/+++/0.```````````````````-////////////++++++++")
print ("0000000000000000000///////00000000////////////////////++++++++++++++++/0.````..--//////0-.-0/+//+.`  ``.-///0-``````````````.....-000000/////+++++++++")
print ("000000000000000000000000//////////////////////////////////+//+++++++++++//////////++++///0-.--0-00-````...//00-.```````````..-----00--..-///++++++++++")
print ("0000000000000000000000000000///////////////////////////////////////+++++++++++/////////00000---0////000/00///00--.````````..---0000/000--0//00////++++")
print ("000000000000000000000000000000000////////////////////////////////////////////+++++/////0000-------000/////////00000-..-----000------0--0000000////////")
print ("-00000000000000000000000000000000000000/////////////////////////////////////////////////////////////0/0000000/////00000000000--.......---0000000/000--")
print ("-------0000000000000000000000000000000000000000///0//0//////////////////////////////////0///////////////////////////////////////000----0000//////////0")
print ("----------------0000000000000000000000000--......``````-000////000//0----0000///////--.--...---00-.-0///00////////////////////////////////00000000000-")
print ("-------------0000////++++++oooooooosssssssssssssssoooo++o++++///000/0000000---00////0--.-.....--00-.----...-0/0000/0----.``.-00---0----0-0----...-----")
print ("//0000///+++oooooooooooooooooooooossssssssssssssssyyyyyyhhhhhhhhhhhhhyyysssooo++++////////00-..```.--..-0000-0-.--...`......-......```.---.````.`-0000")
print ("++++++++++++++++++++oooooooooooooosssssssssssssssssssssyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhyyyso+//00---...-0-.....--........-----000---0000000-..--0000//")
print ("++++++++++++ooooooooooooooooooooossssssssssssssssssyysyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhddddddddddddhhhyysoo++//0-...............--.-------0----000000/")
print ("+++++++++++ooooooooooooooooooosoooossssssssssssssssssssssssyssssyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhdddddddddddddddhhhhhyysooo+//+///00000////+ooso+//00/+")
print ("ooooooo+oooooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhddddddddddddddddddddhhhhhhhhyyhhyhyyyyssyy")
print ("oooooooooooooooooooooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddhddhhh")
print ("sssssssssssoooooooooooooooooooooooooooooooooooooooooosooooooossssoooossssssssssssssssssyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhdddddddddddddddddddddddddddddd")
print ("sssssssssssssssssssoossosssooossssssssssssssooooooooossoooooooooooooooossssssssssssssssssssssssssyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh")
print ("yyyyyyyssssssssssssssssssssssssssssssssssssssosssoosssssssssossssoosoooosssosoooossossoosssssssssssssssssssssssssssyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhh")
print ("yyyyyyyyyyyyyyyyyyyysyyysssssssssssssssssssssssssssssssssssssssssssssososssssssssssssoooooooooooooooooossssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyhhhh")
print ("hhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyysssssssyysyyyyyssssssssssssssssssssssssssssosssssssssooosooooooooooooooossssssssssssssyssyyyyyyyyyyyyyyyyyyyyyyy")
print ("hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysysyssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssyssyssyyysssss")
print ("dddddddddddhhhdddddhdddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssssssssssssssssssssyyyss")
print ("dddddddddddddddddddddddddddddddddddddddddddddhddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhyhhhhhyhyyyyyyyyyyyyyyyyyyyysssyssssssssssssssssssssssssssssssssssssssy")
print ("mmmmmmmmmdmmdddddddddddddddddddddddddddddddddddddddddddddddddddhhhdhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy")
print ("mmmmmmmmmmdmdddddddddmddmdddddddddddddddddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyhyyyyhhhhhhhhhhhyhyhhhhhhhhhhhhdddhddddddddddddhdddhhhhhh")
print ("mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmmmmmdmmmmddddddddddddddddhddddddddddddddddddhddddddhhhhdhhhhddhhddhdhdddhdddddhhdddddddhhhddddddddddddddddddddddddddd")
print ("mNmmmmmmmmmmmmmmmmmddddddddddddddddddddddddddddddhdhdddddddddhhdddddddddddddhhhhddhhhhhdhhdhdddddhdddddddddddddddddddddddhdddddddddddddddddddddddddddd")
print ("ddddmddddddddddddddddddddddddddddddddddhdddddhhhhhddddddddddddhhhhhdhhdhdddddddhddhdddhddddddddddhdddddddddddhdddddddddddddddddddddddddddddddddddddddd")
print ("dddddddddddddddddddddddddhdhhdhhdddddhdddddddddddddddddddddddddddddddddddddhdddhddhhddhddddhdddhddddddddddddddddddddddddddddddddddddddhddddddddddddddd")
print ("ddddddddhhddddhhhdhddddddddddddddddddddddddddddddddddddddhddhhhhdhhhdhhhdhhhhhhdhhhddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd")
print ("dddddddddddddddddddddddddddddddhdddhhddddhddddddhdddhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmdddddddmdd")
print ("ddddddddddddddddddhhdddddddddddhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd")
print ("dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd")
print ("dddmdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddhdddddddddddddddddddddddddddddddddd")
print ("dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddhdhddddddddddddddddddddddddddddddddddddddmddddddddddddddddddddddddd")
print ("ddddddddddddddddddddddmddddddddddmdddddddddddddddhddddddddddddddddhddhhhdddhhhhhdddddddddddddddddddddddddddddddhhhddddddddddddddddddddddddddddddddmddd")
print ("ddmddddmdddddddddddddddddddddddddddddddhdhddhhhhhhhdddhhhdhhhhddddddddhdddddhdddddhhddhhhdhddddhhhhdddddhdhdhdddddddddddddddddddddddddddddddddmddddmmd")
print (" ")
prevquest = input(str("Do you like this image? Y/N "))
if (prevquest == Y):
	print ("Glad you enjoyed!")
else:
	print ("Sorry about that :/")