in1 = str
print ("Command testing")
print ("Test the compatibility log command")
print ("Type 'COMPBLOG' to try out the command!")
print ("Warning! Commands are CaSe SeNsItIvE")
in1 = str(input("FC://"))
if in1 == ("COMPBLOG"):
	print ("File compatibility for MEDOS HDD")
	print ("Documents")
	print ("RTF")
	print ("TXT")
	print ("XPS")
	print ("ODS")
	print ("ODT")
	print ("ODX")
	print ("PDF")
	print ("Images")
	print ("BMP")
	print ("DMP")
	print ("PNG")
	print ("JPEG")
	print ("JPE")
	print ("JFIF")
	print ("GIF")
	print ("TIF")
	print ("TIFF")
	print ("SVG")
	print ("PSD")
	print ("ICO")
	print ("ICN")
	print ("PNS")
	print ("Videos")
	print ("MP4")
	print ("MP2")
	print ("AVI")
	print ("WMV")
	print ("3GP")
	print ("WEBM")
	print ("WLMP")
	print ("WMMP")
	print ("MOV")
	print ("M4V")
	print ("MKV")
	print ("Music")
	print ("OGG")
	print ("MP3")
	print ("MID")
	print ("MIDI")
	print ("FLAC")
	print ("WAV")
	print ("System")
	print ("SYS")
	print ("PY")
	print ("BAT")
	print ("DAT")
	print ("INI")
	print ("SLN")
	print ("EXE")
	print ("0")
	print ("Media")
	print ("IMG")
	print ("IMAGE")
	print ("ISO")
	print ("ZIP")
	print ("7Z")
	print ("TAR")
	print ("RAR")
	print ("ISO")
	print ("DMG")
	print ("Other")
	print ("URL")
	print ("INK")
	print ("TORRENT")
	print (in1)
testconfirm = int(input("Did the command info look right? type 1 to confirm, type anything else and/or press enter to quit "))
if testconfirm == 1:
    print ("Test successful!")
    print ("Shutting down, please wait")
else:
    print ("Shutting down")
   